// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_object_content.proto

package deviced

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetObjectContentRequest struct {
	Object               *OpObject `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetObjectContentRequest) Reset()         { *m = GetObjectContentRequest{} }
func (m *GetObjectContentRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectContentRequest) ProtoMessage()    {}
func (*GetObjectContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38a252548b95948, []int{0}
}

func (m *GetObjectContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectContentRequest.Unmarshal(m, b)
}
func (m *GetObjectContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectContentRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectContentRequest.Merge(m, src)
}
func (m *GetObjectContentRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectContentRequest.Size(m)
}
func (m *GetObjectContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectContentRequest proto.InternalMessageInfo

func (m *GetObjectContentRequest) GetObject() *OpObject {
	if m != nil {
		return m.Object
	}
	return nil
}

type GetObjectContentResponse struct {
	Content              *wrappers.BytesValue `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetObjectContentResponse) Reset()         { *m = GetObjectContentResponse{} }
func (m *GetObjectContentResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectContentResponse) ProtoMessage()    {}
func (*GetObjectContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e38a252548b95948, []int{1}
}

func (m *GetObjectContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectContentResponse.Unmarshal(m, b)
}
func (m *GetObjectContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectContentResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectContentResponse.Merge(m, src)
}
func (m *GetObjectContentResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectContentResponse.Size(m)
}
func (m *GetObjectContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectContentResponse proto.InternalMessageInfo

func (m *GetObjectContentResponse) GetContent() *wrappers.BytesValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*GetObjectContentRequest)(nil), "ai.metathings.service.deviced.GetObjectContentRequest")
	proto.RegisterType((*GetObjectContentResponse)(nil), "ai.metathings.service.deviced.GetObjectContentResponse")
}

func init() { proto.RegisterFile("get_object_content.proto", fileDescriptor_e38a252548b95948) }

var fileDescriptor_e38a252548b95948 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x86, 0x20, 0xb9, 0x5b, 0x16, 0xa2, 0x22, 0xa0, 0xea, 0x02, 0x4b, 0xcf, 0x12,
	0x08, 0x7e, 0x40, 0x19, 0x3a, 0x56, 0x64, 0x60, 0xad, 0xec, 0xe4, 0x70, 0x0d, 0x49, 0xce, 0xd8,
	0x97, 0x46, 0xfc, 0x5a, 0x24, 0x7e, 0x09, 0x22, 0x76, 0x59, 0x90, 0x98, 0x6c, 0xeb, 0xde, 0xf3,
	0xfb, 0xde, 0x89, 0xd2, 0x20, 0xef, 0x48, 0xbf, 0x62, 0xcd, 0xbb, 0x9a, 0x7a, 0xc6, 0x9e, 0xc1,
	0x79, 0x62, 0x2a, 0x2e, 0x94, 0x85, 0x0e, 0x59, 0xf1, 0xde, 0xf6, 0x26, 0x40, 0x40, 0x7f, 0xb0,
	0x35, 0x42, 0x83, 0x3f, 0x47, 0x33, 0xbf, 0x34, 0x44, 0xa6, 0x45, 0x39, 0x89, 0xf5, 0xf0, 0x22,
	0x47, 0xaf, 0x9c, 0x43, 0x1f, 0xa2, 0x7d, 0xfe, 0x60, 0x2c, 0xef, 0x07, 0x0d, 0x35, 0x75, 0xb2,
	0x1b, 0x2d, 0xbf, 0xd1, 0x28, 0x0d, 0xad, 0xa6, 0xe1, 0xea, 0xa0, 0x5a, 0xdb, 0x28, 0x26, 0x1f,
	0xe4, 0xef, 0x35, 0xf9, 0x66, 0x1d, 0x35, 0xd8, 0xc6, 0xc7, 0x52, 0x8b, 0xb3, 0x0d, 0xf2, 0x76,
	0xc2, 0x7b, 0x8c, 0x74, 0x15, 0xbe, 0x0f, 0x18, 0xb8, 0xd8, 0x88, 0x3c, 0x62, 0x97, 0xd9, 0x22,
	0xbb, 0x99, 0xdd, 0x5e, 0xc3, 0xbf, 0xbc, 0xb0, 0x75, 0xf1, 0x9b, 0x75, 0xfe, 0xf5, 0x79, 0x75,
	0xb2, 0xc8, 0xaa, 0x64, 0x5f, 0x3e, 0x89, 0xf2, 0x6f, 0x46, 0x70, 0xd4, 0x07, 0x2c, 0xee, 0xc5,
	0x69, 0x5a, 0x4a, 0x4a, 0x39, 0x87, 0x58, 0x1b, 0x8e, 0xb5, 0x61, 0xfd, 0xc1, 0x18, 0x9e, 0x55,
	0x3b, 0x60, 0x75, 0xd4, 0xea, 0x7c, 0x9a, 0xde, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x0f,
	0xc3, 0x7e, 0x5d, 0x01, 0x00, 0x00,
}
