/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ai.metathings.service.deviced.PullFrameFromFlowRequest');
goog.provide('proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ai.metathings.service.deviced.OpDevice');
goog.require('proto.google.protobuf.BoolValue');
goog.require('proto.google.protobuf.StringValue');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.oneofGroups_);
};
goog.inherits(proto.ai.metathings.service.deviced.PullFrameFromFlowRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.displayName = 'proto.ai.metathings.service.deviced.PullFrameFromFlowRequest';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.oneofGroups_ = [[2]];

/**
 * @enum {number}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  CONFIG: 2
};

/**
 * @return {proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.RequestCase}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.getRequestCase = function() {
  return /** @type {proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    config: (f = msg.getConfig()) && proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.deviced.PullFrameFromFlowRequest;
  return proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config;
      reader.readMessage(value,proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.displayName = 'proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    device: (f = msg.getDevice()) && proto.ai.metathings.service.deviced.OpDevice.toObject(includeInstance, f),
    configAck: (f = msg.getConfigAck()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config;
  return proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ai.metathings.service.deviced.OpDevice;
      reader.readMessage(value,proto.ai.metathings.service.deviced.OpDevice.deserializeBinaryFromReader);
      msg.setDevice(value);
      break;
    case 2:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setConfigAck(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevice();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ai.metathings.service.deviced.OpDevice.serializeBinaryToWriter
    );
  }
  f = message.getConfigAck();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional OpDevice device = 1;
 * @return {?proto.ai.metathings.service.deviced.OpDevice}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.getDevice = function() {
  return /** @type{?proto.ai.metathings.service.deviced.OpDevice} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.deviced.OpDevice, 1));
};


/** @param {?proto.ai.metathings.service.deviced.OpDevice|undefined} value */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.setDevice = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.clearDevice = function() {
  this.setDevice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.hasDevice = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.BoolValue config_ack = 2;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.getConfigAck = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 2));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.setConfigAck = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.clearConfigAck = function() {
  this.setConfigAck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config.prototype.hasConfigAck = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue id = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.getId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 1));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Config config = 2;
 * @return {?proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.getConfig = function() {
  return /** @type{?proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config, 2));
};


/** @param {?proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.Config|undefined} value */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.setConfig = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.oneofGroups_[0], value);
};


proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.clearConfig = function() {
  this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.deviced.PullFrameFromFlowRequest.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};


