// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pull_frame_from_flow.proto

package deviced

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PullFrameFromFlowRequest struct {
	Id *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*PullFrameFromFlowRequest_Config_
	Request              isPullFrameFromFlowRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *PullFrameFromFlowRequest) Reset()         { *m = PullFrameFromFlowRequest{} }
func (m *PullFrameFromFlowRequest) String() string { return proto.CompactTextString(m) }
func (*PullFrameFromFlowRequest) ProtoMessage()    {}
func (*PullFrameFromFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_124a03978452fcc2, []int{0}
}

func (m *PullFrameFromFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFrameFromFlowRequest.Unmarshal(m, b)
}
func (m *PullFrameFromFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFrameFromFlowRequest.Marshal(b, m, deterministic)
}
func (m *PullFrameFromFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFrameFromFlowRequest.Merge(m, src)
}
func (m *PullFrameFromFlowRequest) XXX_Size() int {
	return xxx_messageInfo_PullFrameFromFlowRequest.Size(m)
}
func (m *PullFrameFromFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFrameFromFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullFrameFromFlowRequest proto.InternalMessageInfo

func (m *PullFrameFromFlowRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type isPullFrameFromFlowRequest_Request interface {
	isPullFrameFromFlowRequest_Request()
}

type PullFrameFromFlowRequest_Config_ struct {
	Config *PullFrameFromFlowRequest_Config `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

func (*PullFrameFromFlowRequest_Config_) isPullFrameFromFlowRequest_Request() {}

func (m *PullFrameFromFlowRequest) GetRequest() isPullFrameFromFlowRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PullFrameFromFlowRequest) GetConfig() *PullFrameFromFlowRequest_Config {
	if x, ok := m.GetRequest().(*PullFrameFromFlowRequest_Config_); ok {
		return x.Config
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PullFrameFromFlowRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PullFrameFromFlowRequest_Config_)(nil),
	}
}

type PullFrameFromFlowRequest_Config struct {
	Device               *OpDevice           `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	ConfigAck            *wrappers.BoolValue `protobuf:"bytes,2,opt,name=config_ack,json=configAck,proto3" json:"config_ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PullFrameFromFlowRequest_Config) Reset()         { *m = PullFrameFromFlowRequest_Config{} }
func (m *PullFrameFromFlowRequest_Config) String() string { return proto.CompactTextString(m) }
func (*PullFrameFromFlowRequest_Config) ProtoMessage()    {}
func (*PullFrameFromFlowRequest_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_124a03978452fcc2, []int{0, 0}
}

func (m *PullFrameFromFlowRequest_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFrameFromFlowRequest_Config.Unmarshal(m, b)
}
func (m *PullFrameFromFlowRequest_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFrameFromFlowRequest_Config.Marshal(b, m, deterministic)
}
func (m *PullFrameFromFlowRequest_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFrameFromFlowRequest_Config.Merge(m, src)
}
func (m *PullFrameFromFlowRequest_Config) XXX_Size() int {
	return xxx_messageInfo_PullFrameFromFlowRequest_Config.Size(m)
}
func (m *PullFrameFromFlowRequest_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFrameFromFlowRequest_Config.DiscardUnknown(m)
}

var xxx_messageInfo_PullFrameFromFlowRequest_Config proto.InternalMessageInfo

func (m *PullFrameFromFlowRequest_Config) GetDevice() *OpDevice {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *PullFrameFromFlowRequest_Config) GetConfigAck() *wrappers.BoolValue {
	if m != nil {
		return m.ConfigAck
	}
	return nil
}

type PullFrameFromFlowResponse struct {
	// stream alive check when id is ffffffffffffffffffffffffffffffff,
	// drop it in receive side.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*PullFrameFromFlowResponse_Ack_
	//	*PullFrameFromFlowResponse_Pack_
	Response             isPullFrameFromFlowResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *PullFrameFromFlowResponse) Reset()         { *m = PullFrameFromFlowResponse{} }
func (m *PullFrameFromFlowResponse) String() string { return proto.CompactTextString(m) }
func (*PullFrameFromFlowResponse) ProtoMessage()    {}
func (*PullFrameFromFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_124a03978452fcc2, []int{1}
}

func (m *PullFrameFromFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFrameFromFlowResponse.Unmarshal(m, b)
}
func (m *PullFrameFromFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFrameFromFlowResponse.Marshal(b, m, deterministic)
}
func (m *PullFrameFromFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFrameFromFlowResponse.Merge(m, src)
}
func (m *PullFrameFromFlowResponse) XXX_Size() int {
	return xxx_messageInfo_PullFrameFromFlowResponse.Size(m)
}
func (m *PullFrameFromFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFrameFromFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullFrameFromFlowResponse proto.InternalMessageInfo

func (m *PullFrameFromFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isPullFrameFromFlowResponse_Response interface {
	isPullFrameFromFlowResponse_Response()
}

type PullFrameFromFlowResponse_Ack_ struct {
	Ack *PullFrameFromFlowResponse_Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type PullFrameFromFlowResponse_Pack_ struct {
	Pack *PullFrameFromFlowResponse_Pack `protobuf:"bytes,3,opt,name=pack,proto3,oneof"`
}

func (*PullFrameFromFlowResponse_Ack_) isPullFrameFromFlowResponse_Response() {}

func (*PullFrameFromFlowResponse_Pack_) isPullFrameFromFlowResponse_Response() {}

func (m *PullFrameFromFlowResponse) GetResponse() isPullFrameFromFlowResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *PullFrameFromFlowResponse) GetAck() *PullFrameFromFlowResponse_Ack {
	if x, ok := m.GetResponse().(*PullFrameFromFlowResponse_Ack_); ok {
		return x.Ack
	}
	return nil
}

func (m *PullFrameFromFlowResponse) GetPack() *PullFrameFromFlowResponse_Pack {
	if x, ok := m.GetResponse().(*PullFrameFromFlowResponse_Pack_); ok {
		return x.Pack
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PullFrameFromFlowResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PullFrameFromFlowResponse_Ack_)(nil),
		(*PullFrameFromFlowResponse_Pack_)(nil),
	}
}

type PullFrameFromFlowResponse_Ack struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullFrameFromFlowResponse_Ack) Reset()         { *m = PullFrameFromFlowResponse_Ack{} }
func (m *PullFrameFromFlowResponse_Ack) String() string { return proto.CompactTextString(m) }
func (*PullFrameFromFlowResponse_Ack) ProtoMessage()    {}
func (*PullFrameFromFlowResponse_Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_124a03978452fcc2, []int{1, 0}
}

func (m *PullFrameFromFlowResponse_Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFrameFromFlowResponse_Ack.Unmarshal(m, b)
}
func (m *PullFrameFromFlowResponse_Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFrameFromFlowResponse_Ack.Marshal(b, m, deterministic)
}
func (m *PullFrameFromFlowResponse_Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFrameFromFlowResponse_Ack.Merge(m, src)
}
func (m *PullFrameFromFlowResponse_Ack) XXX_Size() int {
	return xxx_messageInfo_PullFrameFromFlowResponse_Ack.Size(m)
}
func (m *PullFrameFromFlowResponse_Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFrameFromFlowResponse_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_PullFrameFromFlowResponse_Ack proto.InternalMessageInfo

type PullFrameFromFlowResponse_Pack struct {
	Flow                 *Flow    `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	Frames               []*Frame `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullFrameFromFlowResponse_Pack) Reset()         { *m = PullFrameFromFlowResponse_Pack{} }
func (m *PullFrameFromFlowResponse_Pack) String() string { return proto.CompactTextString(m) }
func (*PullFrameFromFlowResponse_Pack) ProtoMessage()    {}
func (*PullFrameFromFlowResponse_Pack) Descriptor() ([]byte, []int) {
	return fileDescriptor_124a03978452fcc2, []int{1, 1}
}

func (m *PullFrameFromFlowResponse_Pack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFrameFromFlowResponse_Pack.Unmarshal(m, b)
}
func (m *PullFrameFromFlowResponse_Pack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFrameFromFlowResponse_Pack.Marshal(b, m, deterministic)
}
func (m *PullFrameFromFlowResponse_Pack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFrameFromFlowResponse_Pack.Merge(m, src)
}
func (m *PullFrameFromFlowResponse_Pack) XXX_Size() int {
	return xxx_messageInfo_PullFrameFromFlowResponse_Pack.Size(m)
}
func (m *PullFrameFromFlowResponse_Pack) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFrameFromFlowResponse_Pack.DiscardUnknown(m)
}

var xxx_messageInfo_PullFrameFromFlowResponse_Pack proto.InternalMessageInfo

func (m *PullFrameFromFlowResponse_Pack) GetFlow() *Flow {
	if m != nil {
		return m.Flow
	}
	return nil
}

func (m *PullFrameFromFlowResponse_Pack) GetFrames() []*Frame {
	if m != nil {
		return m.Frames
	}
	return nil
}

func init() {
	proto.RegisterType((*PullFrameFromFlowRequest)(nil), "ai.metathings.service.deviced.PullFrameFromFlowRequest")
	proto.RegisterType((*PullFrameFromFlowRequest_Config)(nil), "ai.metathings.service.deviced.PullFrameFromFlowRequest.Config")
	proto.RegisterType((*PullFrameFromFlowResponse)(nil), "ai.metathings.service.deviced.PullFrameFromFlowResponse")
	proto.RegisterType((*PullFrameFromFlowResponse_Ack)(nil), "ai.metathings.service.deviced.PullFrameFromFlowResponse.Ack")
	proto.RegisterType((*PullFrameFromFlowResponse_Pack)(nil), "ai.metathings.service.deviced.PullFrameFromFlowResponse.Pack")
}

func init() { proto.RegisterFile("pull_frame_from_flow.proto", fileDescriptor_124a03978452fcc2) }

var fileDescriptor_124a03978452fcc2 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0xc6, 0x9b, 0xa4, 0x8d, 0xed, 0x29, 0x88, 0xcc, 0xc6, 0x18, 0x54, 0x4a, 0x15, 0xec, 0x6a,
	0x0a, 0x15, 0x14, 0xa1, 0x2a, 0x8d, 0x52, 0xba, 0xb3, 0xa4, 0x20, 0xee, 0xc2, 0x34, 0x99, 0xc4,
	0x21, 0x93, 0x4c, 0x9c, 0x24, 0xed, 0xca, 0x9d, 0x2b, 0x1f, 0xca, 0xa7, 0xf1, 0x29, 0x5c, 0x49,
	0x66, 0xa6, 0xf7, 0x2e, 0xee, 0x9f, 0x72, 0xef, 0x2a, 0x93, 0xc9, 0xf9, 0x7e, 0xdf, 0x77, 0x4e,
	0x0e, 0xf8, 0x55, 0xcb, 0x79, 0x94, 0x4a, 0x52, 0xd0, 0x28, 0x95, 0xa2, 0x88, 0x52, 0x2e, 0x8e,
	0xb8, 0x92, 0xa2, 0x11, 0xe8, 0x19, 0x61, 0xb8, 0xa0, 0x0d, 0x69, 0xbe, 0xb3, 0x32, 0xab, 0x71,
	0x4d, 0xe5, 0x81, 0xc5, 0x14, 0x27, 0xb4, 0x7b, 0x24, 0xfe, 0xf3, 0x4c, 0x88, 0x8c, 0xd3, 0xb9,
	0x2a, 0xde, 0xb7, 0xe9, 0xfc, 0x28, 0x49, 0x55, 0x51, 0x59, 0x6b, 0xb9, 0xff, 0xf8, 0x40, 0x38,
	0x4b, 0x48, 0x43, 0xe7, 0xa7, 0x83, 0xf9, 0x30, 0x2e, 0x44, 0x42, 0xb9, 0x7e, 0x99, 0xfe, 0xb1,
	0xc1, 0xdb, 0xb6, 0x9c, 0xaf, 0xbb, 0x08, 0x6b, 0x29, 0x8a, 0x35, 0x17, 0xc7, 0x90, 0xfe, 0x68,
	0x69, 0xdd, 0xa0, 0x37, 0x60, 0xb3, 0xc4, 0xb3, 0x26, 0xd6, 0x6c, 0xbc, 0x78, 0x8a, 0xb5, 0x1f,
	0x3e, 0xf9, 0xe1, 0x5d, 0x23, 0x59, 0x99, 0x7d, 0x25, 0xbc, 0xa5, 0xc1, 0xf0, 0x5f, 0x30, 0xf8,
	0x6d, 0xd9, 0x8f, 0xac, 0xd0, 0x66, 0x09, 0xfa, 0x06, 0x6e, 0x2c, 0xca, 0x94, 0x65, 0x9e, 0xad,
	0xb4, 0x1f, 0xf0, 0xad, 0xad, 0xe0, 0x9b, 0x02, 0xe0, 0x4f, 0x8a, 0xb2, 0xe9, 0x85, 0x86, 0xe7,
	0xff, 0xb2, 0xc0, 0xd5, 0x97, 0xe8, 0x23, 0xb8, 0x5a, 0x6f, 0x02, 0xbe, 0x3a, 0x63, 0xf2, 0xa5,
	0xfa, 0xac, 0x4e, 0xa1, 0x91, 0xa1, 0x77, 0x00, 0x9a, 0x1a, 0x91, 0x38, 0x37, 0x49, 0xfd, 0x2b,
	0x5d, 0x06, 0x42, 0x70, 0xd5, 0x63, 0x38, 0xd2, 0xd5, 0xab, 0x38, 0x0f, 0x46, 0xf0, 0x40, 0xea,
	0x88, 0xd3, 0xbf, 0x36, 0x3c, 0xb9, 0x26, 0x7f, 0x5d, 0x89, 0xb2, 0xa6, 0xe8, 0xe1, 0xc5, 0x04,
	0x47, 0x6a, 0x32, 0x5b, 0x70, 0x2e, 0xcd, 0x96, 0x77, 0x1f, 0x8b, 0xc6, 0xe2, 0x55, 0x9c, 0x6f,
	0x7a, 0x61, 0x87, 0x42, 0x3b, 0xe8, 0x57, 0x1d, 0xd2, 0x51, 0xc8, 0xf7, 0xf7, 0x46, 0x6e, 0x89,
	0x62, 0x2a, 0x98, 0x3f, 0x00, 0x67, 0x15, 0xe7, 0xfe, 0x4f, 0xe8, 0x77, 0xd7, 0xe8, 0x2d, 0xf4,
	0xbb, 0xbd, 0x34, 0x83, 0x7e, 0x71, 0xc6, 0x43, 0x61, 0x95, 0x00, 0x2d, 0xc1, 0x55, 0xbb, 0x5d,
	0x7b, 0xf6, 0xc4, 0x99, 0x8d, 0x17, 0x2f, 0xcf, 0x49, 0xbb, 0xe2, 0xd0, 0x68, 0x02, 0x80, 0xa1,
	0x34, 0xf1, 0xf6, 0xae, 0xfa, 0x21, 0xaf, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x21, 0x4b, 0xb1,
	0x0f, 0x31, 0x03, 0x00, 0x00,
}
