version: "3"
services:

  metathings:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.frontd
    image: nayotta/metathings-frontd
    volumes:
    - ./etc/envoy.front.yaml:/etc/envoy.front.yaml
    networks:
    - metathings-frontend
    - metathings-backend
    expose:
    - "21733"
    - "8001"
    ports:
    - "21733:21733"
    - "8001:8001"
    restart: on-failure

  policyd:
    environment:
    - MTD_STAGE=dev
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.policyd.dev
    image: nayotta/metathings-policyd-development
    volumes:
    - .:/go/src/github.com/nayotta/metathings
    - ./data/storage:/var/metathings/storage
    - ./etc/policyd.yaml:/etc/metathings/policyd.yaml
    - ./etc/policyd-model.conf:/etc/metathings/policyd-model.conf
    - ./etc/policyd-policy.csv:/etc/metathings/policyd-policy.csv
    - ./cert/policyd-server.crt:/etc/metathings/cert/policyd-server.crt
    - ./cert/policyd-server.key:/etc/metathings/cert/policyd-server.key
    networks:
    - metathings-policy
    expose:
    - "4001"
    restart: on-failure

  identityd:
    environment:
    - MTD_STAGE=dev
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.identityd.dev
    image: nayotta/metathings-identityd-development
    volumes:
    - .:/go/src/github.com/nayotta/metathings
    - ./etc/identityd.yaml:/etc/metathings/identityd.yaml
    networks:
    - metathings-backend
    expose:
    - "5000"
    restart: on-failure

  cored:
    environment:
    - MTD_STAGE=dev
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.cored.dev
    image: nayotta/metathings-cored-development
    volumes:
    - ./data/storage:/var/metathings/storage
    - .:/go/src/github.com/nayotta/metathings
    - ./etc/cored.yaml:/etc/metathings/cored.yaml
    networks:
    - metathings-backend
    expose:
    - "5001"
    restart: on-failure

  camerad:
    environment:
    - MTD_STAGE=dev
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.camerad.dev
    image: nayotta/metathings-camerad-development
    volumes:
    - ./data/storage:/var/metathings/storage
    - .:/go/src/github.com/nayotta/metathings
    - ./etc/camerad.yaml:/etc/metathings/camerad.yaml
    networks:
    - metathings-backend
    expose:
    - "5002"
    restart: on-failure

  sensord:
    environment:
    - MTD_STAGE=dev
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.sensord.dev
    image: nayotta/metathings-sensord-development
    volumes:
    - ./data/storage:/var/metathings/storage
    - .:/go/src/github.com/nayotta/metathings
    - ./etc/sensord.yaml:/etc/metathings/sensord.yaml
    networks:
    - metathings-backend
    - metathings-kafka
    expose:
    - "5003"
    restart: on-failure

  streamd:
    environment:
    - MTD_STAGE=dev
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.streamd.dev
    image: nayotta/metathings-streamd-development
    volumes:
    - ./data/storage:/var/metathings/storage
    - .:/go/src/github.com/nayotta/metathings
    - ./etc/streamd.yaml:/etc/metathings/streamd.yaml
    networks:
    - metathings-backend
    - metathings-kafka
    expose:
    - "5004"
    restart: on-failure

networks:
  metathings-frontend:
    external:
      name: metathings-frontend
  metathings-backend:
    external:
      name: metathings-backend
  metathings-kafka:
    external:
      name: metathings-kafka
  metathings-policy:
    external:
      name: metathings-policy
