version: '2'
services:

  metathings:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.frontd
    image: bigdatagz/frontd
    volumes:
      - ./etc/envoy.front.yaml:/etc/envoy.front.yaml
    networks:
      metathingsmesh: {}
    expose:
      - "80"
      - "8001"
    ports:
      - "80:80"
      - "8001:8001"
    restart: on-failure

  identityd:
    environment:
      - MTD_STAGE=dev
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.identityd.dev
    image: bigdatagz/metathings-identityd-development
    volumes:
      - .:/go/src/github.com/bigdatagz/metathings
      - ./etc/identityd.yaml:/etc/metathings/identityd.yaml
    networks:
      metathingsmesh: {}
    ports:
      - "5000:5000"
    expose:
      - "5000"
    restart: on-failure

  cored:
    environment:
      - MTD_STAGE=dev
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.cored.dev
    image: bigdatagz/metathings-cored-development
    volumes:
      - ./data/storage:/var/metathings/storage
      - .:/go/src/github.com/bigdatagz/metathings
      - ./etc/cored.yaml:/etc/metathings/cored.yaml
    networks:
      metathingsmesh: {}
    ports:
      - "5001:5001"
    expose:
      - "5001"
    restart: on-failure

networks:
  metathingsmesh: {}
