// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heartbeat_select.proto

package device_cloud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeartBeatSelectRequest struct {
	ComponentId          *wrappers.StringValue `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HeartBeatSelectRequest) Reset()         { *m = HeartBeatSelectRequest{} }
func (m *HeartBeatSelectRequest) String() string { return proto.CompactTextString(m) }
func (*HeartBeatSelectRequest) ProtoMessage()    {}
func (*HeartBeatSelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d3f834ff993c5c, []int{0}
}

func (m *HeartBeatSelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatSelectRequest.Unmarshal(m, b)
}
func (m *HeartBeatSelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatSelectRequest.Marshal(b, m, deterministic)
}
func (m *HeartBeatSelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatSelectRequest.Merge(m, src)
}
func (m *HeartBeatSelectRequest) XXX_Size() int {
	return xxx_messageInfo_HeartBeatSelectRequest.Size(m)
}
func (m *HeartBeatSelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatSelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatSelectRequest proto.InternalMessageInfo

func (m *HeartBeatSelectRequest) GetComponentId() *wrappers.StringValue {
	if m != nil {
		return m.ComponentId
	}
	return nil
}

type HeartBeatSelectResponse struct {
	ResCode              int32    `protobuf:"varint,1,opt,name=res_code,json=resCode,proto3" json:"res_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatSelectResponse) Reset()         { *m = HeartBeatSelectResponse{} }
func (m *HeartBeatSelectResponse) String() string { return proto.CompactTextString(m) }
func (*HeartBeatSelectResponse) ProtoMessage()    {}
func (*HeartBeatSelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d3f834ff993c5c, []int{1}
}

func (m *HeartBeatSelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatSelectResponse.Unmarshal(m, b)
}
func (m *HeartBeatSelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatSelectResponse.Marshal(b, m, deterministic)
}
func (m *HeartBeatSelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatSelectResponse.Merge(m, src)
}
func (m *HeartBeatSelectResponse) XXX_Size() int {
	return xxx_messageInfo_HeartBeatSelectResponse.Size(m)
}
func (m *HeartBeatSelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatSelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatSelectResponse proto.InternalMessageInfo

func (m *HeartBeatSelectResponse) GetResCode() int32 {
	if m != nil {
		return m.ResCode
	}
	return 0
}

func init() {
	proto.RegisterType((*HeartBeatSelectRequest)(nil), "ai.metathings.service.device_cloud.HeartBeatSelectRequest")
	proto.RegisterType((*HeartBeatSelectResponse)(nil), "ai.metathings.service.device_cloud.HeartBeatSelectResponse")
}

func init() { proto.RegisterFile("heartbeat_select.proto", fileDescriptor_51d3f834ff993c5c) }

var fileDescriptor_51d3f834ff993c5c = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0x60, 0x95, 0xd4, 0x53, 0x0e, 0x55, 0x8b, 0x68, 0xc9, 0xc9, 0x4b, 0x37, 0xa0,
	0xe2, 0x0f, 0xa8, 0x07, 0xf5, 0x9a, 0x82, 0xd7, 0xb0, 0xd9, 0x7d, 0x6e, 0x16, 0x93, 0x4c, 0xdc,
	0x99, 0x34, 0x3f, 0x57, 0xf0, 0x97, 0x48, 0x13, 0xec, 0xa5, 0xa7, 0x19, 0x78, 0x7c, 0xef, 0x7d,
	0xf1, 0xa2, 0x82, 0x0e, 0x52, 0x42, 0x4b, 0xc1, 0xa8, 0x61, 0x44, 0x75, 0x81, 0x84, 0x92, 0x54,
	0x7b, 0xd5, 0x40, 0xb4, 0x54, 0xbe, 0x75, 0xac, 0x18, 0x61, 0xe7, 0x0d, 0x94, 0xc5, 0xfe, 0x14,
	0xa6, 0xa6, 0xde, 0x2e, 0x6f, 0x1d, 0x91, 0xab, 0x91, 0x8d, 0x44, 0xd9, 0x7f, 0x66, 0x43, 0xd0,
	0x5d, 0x87, 0xc0, 0x53, 0xc7, 0xf2, 0xd9, 0x79, 0xa9, 0xfa, 0x52, 0x19, 0x6a, 0xb2, 0x66, 0xf0,
	0xf2, 0x45, 0x43, 0xe6, 0x68, 0x3d, 0x86, 0xeb, 0x9d, 0xae, 0xbd, 0xd5, 0x42, 0x81, 0xb3, 0xc3,
	0x3b, 0x71, 0xa9, 0x8e, 0x17, 0x6f, 0x7b, 0xab, 0x0d, 0xb4, 0x6c, 0x47, 0xa9, 0x1c, 0xdf, 0x3d,
	0x58, 0x92, 0xd7, 0xf8, 0xc2, 0x50, 0xd3, 0x51, 0x8b, 0x56, 0x0a, 0x6f, 0xaf, 0xa2, 0x55, 0x74,
	0x3f, 0x7f, 0xb8, 0x51, 0x93, 0x88, 0xfa, 0x17, 0x51, 0x5b, 0x09, 0xbe, 0x75, 0x1f, 0xba, 0xee,
	0xb1, 0x99, 0xfd, 0xfe, 0xdc, 0x9d, 0xac, 0xa2, 0x7c, 0x7e, 0x20, 0xdf, 0x6d, 0xfa, 0x14, 0x5f,
	0x1e, 0x4d, 0x70, 0x47, 0x2d, 0x23, 0xb9, 0x8e, 0xcf, 0x03, 0xb8, 0x30, 0x64, 0x31, 0xf6, 0x9f,
	0xe6, 0x67, 0x01, 0xfc, 0x42, 0x16, 0xe5, 0x6c, 0x1c, 0x78, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xcb, 0x15, 0xd3, 0x5b, 0x35, 0x01, 0x00, 0x00,
}
