// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remove_firmware_descriptor_from_firmware_hub.proto

package deviced

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RemoveFirmwareDescriptorFromFirmwareHubRequest struct {
	FirmwareHub          *OpFirmwareHub        `protobuf:"bytes,1,opt,name=firmware_hub,json=firmwareHub,proto3" json:"firmware_hub,omitempty"`
	FirmwareDescriptor   *OpFirmwareDescriptor `protobuf:"bytes,2,opt,name=firmware_descriptor,json=firmwareDescriptor,proto3" json:"firmware_descriptor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) Reset() {
	*m = RemoveFirmwareDescriptorFromFirmwareHubRequest{}
}
func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) String() string {
	return proto.CompactTextString(m)
}
func (*RemoveFirmwareDescriptorFromFirmwareHubRequest) ProtoMessage() {}
func (*RemoveFirmwareDescriptorFromFirmwareHubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1a8fc113adc2a7, []int{0}
}

func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFirmwareDescriptorFromFirmwareHubRequest.Unmarshal(m, b)
}
func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFirmwareDescriptorFromFirmwareHubRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFirmwareDescriptorFromFirmwareHubRequest.Merge(m, src)
}
func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFirmwareDescriptorFromFirmwareHubRequest.Size(m)
}
func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFirmwareDescriptorFromFirmwareHubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFirmwareDescriptorFromFirmwareHubRequest proto.InternalMessageInfo

func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) GetFirmwareHub() *OpFirmwareHub {
	if m != nil {
		return m.FirmwareHub
	}
	return nil
}

func (m *RemoveFirmwareDescriptorFromFirmwareHubRequest) GetFirmwareDescriptor() *OpFirmwareDescriptor {
	if m != nil {
		return m.FirmwareDescriptor
	}
	return nil
}

func init() {
	proto.RegisterType((*RemoveFirmwareDescriptorFromFirmwareHubRequest)(nil), "ai.metathings.service.deviced.RemoveFirmwareDescriptorFromFirmwareHubRequest")
}

func init() {
	proto.RegisterFile("remove_firmware_descriptor_from_firmware_hub.proto", fileDescriptor_8b1a8fc113adc2a7)
}

var fileDescriptor_8b1a8fc113adc2a7 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x2a, 0x4a, 0xcd, 0xcd,
	0x2f, 0x4b, 0x8d, 0x4f, 0xcb, 0x2c, 0xca, 0x2d, 0x4f, 0x2c, 0x4a, 0x8d, 0x4f, 0x49, 0x2d, 0x4e,
	0x2e, 0xca, 0x2c, 0x28, 0xc9, 0x2f, 0x8a, 0x4f, 0x2b, 0xca, 0xcf, 0x45, 0x48, 0x64, 0x94, 0x26,
	0xe9, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xc9, 0x26, 0x66, 0xea, 0xe5, 0xa6, 0x96, 0x24, 0x96,
	0x64, 0x64, 0xe6, 0xa5, 0x17, 0xeb, 0x15, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0xea, 0xa5, 0xa4,
	0x82, 0xa8, 0x14, 0x29, 0xf1, 0xb2, 0xc4, 0x9c, 0xcc, 0x94, 0xc4, 0x92, 0x54, 0x7d, 0x18, 0x03,
	0xa2, 0x4f, 0x8a, 0x3b, 0x37, 0x3f, 0x25, 0x35, 0x07, 0xc2, 0x51, 0xfa, 0xcd, 0xc8, 0xa5, 0x17,
	0x04, 0xb6, 0xdb, 0x0d, 0x6a, 0x83, 0x0b, 0xdc, 0x66, 0xb7, 0xa2, 0xfc, 0x5c, 0x98, 0xa8, 0x47,
	0x69, 0x52, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x50, 0x24, 0x17, 0x0f, 0xb2, 0x6b, 0x24,
	0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x74, 0xf4, 0xf0, 0x3a, 0x47, 0xcf, 0xbf, 0x00, 0xc9, 0x28,
	0x27, 0x8e, 0x5f, 0x4e, 0xac, 0x5d, 0x8c, 0x4c, 0x02, 0x8c, 0x41, 0xdc, 0x69, 0x08, 0x61, 0xa1,
	0x3c, 0x2e, 0x61, 0x2c, 0x21, 0x20, 0xc1, 0x04, 0xb6, 0xc1, 0x98, 0x68, 0x1b, 0x10, 0x5e, 0x40,
	0xb2, 0x48, 0x28, 0x0d, 0x43, 0x36, 0x89, 0x0d, 0x1c, 0x08, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0xba, 0x24, 0xfa, 0x7f, 0x01, 0x00, 0x00,
}
