// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create_bundle.proto

package datad

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateBundleRequest struct {
	Bundle               *OpBundle `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateBundleRequest) Reset()         { *m = CreateBundleRequest{} }
func (m *CreateBundleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBundleRequest) ProtoMessage()    {}
func (*CreateBundleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acda28ad41784c55, []int{0}
}

func (m *CreateBundleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBundleRequest.Unmarshal(m, b)
}
func (m *CreateBundleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBundleRequest.Marshal(b, m, deterministic)
}
func (m *CreateBundleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBundleRequest.Merge(m, src)
}
func (m *CreateBundleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBundleRequest.Size(m)
}
func (m *CreateBundleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBundleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBundleRequest proto.InternalMessageInfo

func (m *CreateBundleRequest) GetBundle() *OpBundle {
	if m != nil {
		return m.Bundle
	}
	return nil
}

type CreateBundleResponse struct {
	Bundle               *Bundle  `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBundleResponse) Reset()         { *m = CreateBundleResponse{} }
func (m *CreateBundleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBundleResponse) ProtoMessage()    {}
func (*CreateBundleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acda28ad41784c55, []int{1}
}

func (m *CreateBundleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBundleResponse.Unmarshal(m, b)
}
func (m *CreateBundleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBundleResponse.Marshal(b, m, deterministic)
}
func (m *CreateBundleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBundleResponse.Merge(m, src)
}
func (m *CreateBundleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBundleResponse.Size(m)
}
func (m *CreateBundleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBundleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBundleResponse proto.InternalMessageInfo

func (m *CreateBundleResponse) GetBundle() *Bundle {
	if m != nil {
		return m.Bundle
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateBundleRequest)(nil), "ai.metathings.service.datad.CreateBundleRequest")
	proto.RegisterType((*CreateBundleResponse)(nil), "ai.metathings.service.datad.CreateBundleResponse")
}

func init() { proto.RegisterFile("create_bundle.proto", fileDescriptor_acda28ad41784c55) }

var fileDescriptor_acda28ad41784c55 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x8d, 0x4f, 0x2a, 0xcd, 0x4b, 0xc9, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x92, 0x4e, 0xcc, 0xd4, 0xcb, 0x4d, 0x2d, 0x49, 0x2c, 0xc9, 0xc8, 0xcc, 0x4b, 0x2f, 0xd6, 0x2b,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x4b, 0x49, 0x2c, 0x49, 0x4c, 0x91, 0x32, 0x4b, 0xcf,
	0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x2d, 0xcf, 0x2c, 0xc9, 0xce, 0x2f,
	0xd7, 0x4f, 0xcf, 0xd7, 0x05, 0xeb, 0xd4, 0x2d, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0xc9, 0x2f,
	0x2a, 0xd6, 0x87, 0x33, 0x21, 0x86, 0x4a, 0x71, 0xe7, 0xe6, 0xa7, 0xa4, 0xe6, 0x40, 0x38, 0x4a,
	0x31, 0x5c, 0xc2, 0xce, 0x60, 0x8b, 0x9d, 0xc0, 0xf6, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x08, 0xb9, 0x72, 0xb1, 0x41, 0x1c, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0xa4, 0xaa, 0x87,
	0xc7, 0x25, 0x7a, 0xfe, 0x05, 0x10, 0xdd, 0x4e, 0x6c, 0x8f, 0xee, 0xcb, 0x33, 0x29, 0x30, 0x06,
	0x41, 0x35, 0x2b, 0x05, 0x73, 0x89, 0xa0, 0x9a, 0x5e, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x64,
	0x8d, 0x66, 0xbc, 0x32, 0x5e, 0xe3, 0xa1, 0x9a, 0xa1, 0x5a, 0x92, 0xd8, 0xc0, 0x2e, 0x37, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x2e, 0xcf, 0x1b, 0x32, 0x01, 0x00, 0x00,
}
