// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: i2c_read.proto

package mqttd

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *I2CReadRequest) Validate() error {
	if nil == this.I2C {
		return github_com_mwitkow_go_proto_validators.FieldError("I2C", fmt.Errorf("message must exist"))
	}
	if this.I2C != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.I2C); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("I2C", err)
		}
	}
	return nil
}
func (this *I2CReadResponse) Validate() error {
	if this.I2C != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.I2C); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("I2C", err)
		}
	}
	return nil
}
