// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package mqttd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xb7, 0x07, 0xfe, 0xac, 0xb7, 0x88, 0x25, 0x2b, 0x21, 0x94, 0xbd, 0xed, 0x89, 0x0b,
	0x4e, 0xf9, 0xf7, 0x02, 0x6c, 0x51, 0x39, 0x80, 0x84, 0x28, 0xa8, 0x52, 0x2f, 0x91, 0x9b, 0x0c,
	0x89, 0x25, 0xa7, 0x4e, 0xed, 0x09, 0x55, 0x8f, 0x3c, 0x20, 0xef, 0x84, 0xe2, 0xc4, 0xae, 0x1b,
	0x69, 0x93, 0xf4, 0x3a, 0xf9, 0xcd, 0xf7, 0xf9, 0x9b, 0xb1, 0x43, 0x9e, 0x69, 0x50, 0x7f, 0x78,
	0x02, 0xb4, 0x54, 0x12, 0x65, 0x70, 0xcb, 0x38, 0x2d, 0x00, 0x19, 0xe6, 0x7c, 0x9b, 0x69, 0x6a,
	0x3f, 0x16, 0x3b, 0xc4, 0x34, 0xbc, 0xcd, 0xa4, 0xcc, 0x04, 0x44, 0x06, 0xdd, 0x54, 0xbf, 0x23,
	0x28, 0x4a, 0x3c, 0x34, 0x9d, 0xe1, 0x4d, 0xa2, 0x80, 0x21, 0xc4, 0x29, 0x1c, 0xe5, 0xc2, 0x9b,
	0x14, 0x04, 0x74, 0x8b, 0x41, 0xc9, 0x30, 0xc9, 0x4f, 0x6b, 0xd7, 0x19, 0x60, 0x87, 0x12, 0x5c,
	0xdb, 0x92, 0x6e, 0x6b, 0x2f, 0x74, 0x2e, 0xf7, 0x9d, 0xc6, 0x6a, 0xcb, 0xd4, 0x21, 0x4e, 0x98,
	0x10, 0x0e, 0x42, 0x05, 0xac, 0xf0, 0x4b, 0xcf, 0x73, 0x60, 0x0a, 0x37, 0xc0, 0xb0, 0x2d, 0xbc,
	0xca, 0x4a, 0x2e, 0xe3, 0x94, 0x67, 0x1c, 0x99, 0x88, 0xf7, 0x8a, 0x63, 0xab, 0xf7, 0xee, 0xdf,
	0x53, 0x32, 0xfd, 0x56, 0xa7, 0x5d, 0x36, 0xd1, 0x83, 0x8a, 0x4c, 0xef, 0x4d, 0xb2, 0xb9, 0xb1,
	0x0d, 0x66, 0xb4, 0x67, 0x44, 0xd4, 0x47, 0x7f, 0xc0, 0xae, 0x02, 0x8d, 0xe1, 0xdb, 0x33, 0x3a,
	0x74, 0x29, 0xb7, 0x1a, 0xee, 0x2e, 0x82, 0x35, 0x99, 0xce, 0xcd, 0xec, 0x46, 0xd9, 0xfa, 0xa8,
	0xb5, 0x7d, 0x49, 0x9b, 0x75, 0x51, 0xbb, 0x2e, 0xfa, 0xb9, 0x5e, 0xd7, 0xdd, 0x45, 0xa0, 0xc8,
	0xd5, 0xf7, 0x7a, 0x05, 0xad, 0x74, 0xd4, 0x2b, 0xed, 0x91, 0x56, 0x79, 0x36, 0xbe, 0xc1, 0xe5,
	0x11, 0xe4, 0x72, 0x01, 0xd8, 0x3a, 0xbe, 0xe9, 0x15, 0x70, 0x9c, 0xf5, 0xa3, 0x63, 0x71, 0xe7,
	0xa6, 0xc8, 0xd5, 0x57, 0xae, 0xdb, 0xba, 0x1e, 0x48, 0xe8, 0x91, 0xe3, 0x12, 0x9e, 0x34, 0x38,
	0xcf, 0x9f, 0xe4, 0xf2, 0x8b, 0xbd, 0x66, 0x03, 0x09, 0x1d, 0x37, 0xbc, 0xab, 0x15, 0x21, 0xcb,
	0x5c, 0xee, 0xdb, 0xc1, 0x3d, 0xc0, 0x85, 0xfd, 0x01, 0x8f, 0x02, 0xde, 0x71, 0xff, 0x4e, 0xc8,
	0xf5, 0xa2, 0xe4, 0x72, 0xde, 0x3c, 0x82, 0x55, 0xfd, 0x06, 0x82, 0x0f, 0xfd, 0x93, 0xee, 0xe0,
	0xf6, 0xf4, 0x1f, 0xcf, 0xec, 0xf2, 0x2f, 0xc5, 0xaf, 0xfa, 0xf9, 0xde, 0x33, 0x21, 0x06, 0x46,
	0xe6, 0xb8, 0x71, 0x97, 0xc2, 0xc3, 0x9d, 0x9b, 0x26, 0x64, 0x69, 0x7e, 0x0d, 0xc6, 0xae, 0xbf,
	0xff, 0x08, 0x5a, 0xbf, 0x68, 0x34, 0x6f, 0x0d, 0x5f, 0x4f, 0x66, 0x93, 0x4f, 0x4f, 0xd6, 0x8f,
	0x0c, 0xb1, 0x79, 0x6c, 0x56, 0xf6, 0xfe, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xb6, 0xf9,
	0x83, 0x71, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MqttdServiceClient is the client API for MqttdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MqttdServiceClient interface {
	CreateDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	PatchDevice(ctx context.Context, in *PatchDeviceRequest, opts ...grpc.CallOption) (*PatchDeviceResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ShowDevice(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ShowDeviceResponse, error)
	GpioDigitalWrite(ctx context.Context, in *GpioDigitalWriteRequest, opts ...grpc.CallOption) (*GpioDigitalWriteResponse, error)
	UnaryCall(ctx context.Context, in *UnaryCallRequest, opts ...grpc.CallOption) (*UnaryCallResponse, error)
	StreamCall(ctx context.Context, opts ...grpc.CallOption) (MqttdService_StreamCallClient, error)
}

type mqttdServiceClient struct {
	cc *grpc.ClientConn
}

func NewMqttdServiceClient(cc *grpc.ClientConn) MqttdServiceClient {
	return &mqttdServiceClient{cc}
}

func (c *mqttdServiceClient) CreateDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error) {
	out := new(CreateDeviceResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/CreateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) PatchDevice(ctx context.Context, in *PatchDeviceRequest, opts ...grpc.CallOption) (*PatchDeviceResponse, error) {
	out := new(PatchDeviceResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/PatchDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) ShowDevice(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ShowDeviceResponse, error) {
	out := new(ShowDeviceResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/ShowDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) GpioDigitalWrite(ctx context.Context, in *GpioDigitalWriteRequest, opts ...grpc.CallOption) (*GpioDigitalWriteResponse, error) {
	out := new(GpioDigitalWriteResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/GpioDigitalWrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) UnaryCall(ctx context.Context, in *UnaryCallRequest, opts ...grpc.CallOption) (*UnaryCallResponse, error) {
	out := new(UnaryCallResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.service.mqttd.MqttdService/UnaryCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqttdServiceClient) StreamCall(ctx context.Context, opts ...grpc.CallOption) (MqttdService_StreamCallClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MqttdService_serviceDesc.Streams[0], "/ai.metathings.service.mqttd.MqttdService/StreamCall", opts...)
	if err != nil {
		return nil, err
	}
	x := &mqttdServiceStreamCallClient{stream}
	return x, nil
}

type MqttdService_StreamCallClient interface {
	Send(*StreamCallRequest) error
	Recv() (*StreamCallResponse, error)
	grpc.ClientStream
}

type mqttdServiceStreamCallClient struct {
	grpc.ClientStream
}

func (x *mqttdServiceStreamCallClient) Send(m *StreamCallRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mqttdServiceStreamCallClient) Recv() (*StreamCallResponse, error) {
	m := new(StreamCallResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MqttdServiceServer is the server API for MqttdService service.
type MqttdServiceServer interface {
	CreateDevice(context.Context, *CreateDeviceRequest) (*CreateDeviceResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*empty.Empty, error)
	PatchDevice(context.Context, *PatchDeviceRequest) (*PatchDeviceResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*empty.Empty, error)
	ShowDevice(context.Context, *empty.Empty) (*ShowDeviceResponse, error)
	GpioDigitalWrite(context.Context, *GpioDigitalWriteRequest) (*GpioDigitalWriteResponse, error)
	UnaryCall(context.Context, *UnaryCallRequest) (*UnaryCallResponse, error)
	StreamCall(MqttdService_StreamCallServer) error
}

func RegisterMqttdServiceServer(s *grpc.Server, srv MqttdServiceServer) {
	s.RegisterService(&_MqttdService_serviceDesc, srv)
}

func _MqttdService_CreateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).CreateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/CreateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).CreateDevice(ctx, req.(*CreateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_PatchDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).PatchDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/PatchDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).PatchDevice(ctx, req.(*PatchDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_ShowDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).ShowDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/ShowDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).ShowDevice(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_GpioDigitalWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpioDigitalWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).GpioDigitalWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/GpioDigitalWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).GpioDigitalWrite(ctx, req.(*GpioDigitalWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_UnaryCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqttdServiceServer).UnaryCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.service.mqttd.MqttdService/UnaryCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqttdServiceServer).UnaryCall(ctx, req.(*UnaryCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqttdService_StreamCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MqttdServiceServer).StreamCall(&mqttdServiceStreamCallServer{stream})
}

type MqttdService_StreamCallServer interface {
	Send(*StreamCallResponse) error
	Recv() (*StreamCallRequest, error)
	grpc.ServerStream
}

type mqttdServiceStreamCallServer struct {
	grpc.ServerStream
}

func (x *mqttdServiceStreamCallServer) Send(m *StreamCallResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mqttdServiceStreamCallServer) Recv() (*StreamCallRequest, error) {
	m := new(StreamCallRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MqttdService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ai.metathings.service.mqttd.MqttdService",
	HandlerType: (*MqttdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDevice",
			Handler:    _MqttdService_CreateDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _MqttdService_DeleteDevice_Handler,
		},
		{
			MethodName: "PatchDevice",
			Handler:    _MqttdService_PatchDevice_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _MqttdService_GetDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _MqttdService_ListDevices_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MqttdService_Heartbeat_Handler,
		},
		{
			MethodName: "ShowDevice",
			Handler:    _MqttdService_ShowDevice_Handler,
		},
		{
			MethodName: "GpioDigitalWrite",
			Handler:    _MqttdService_GpioDigitalWrite_Handler,
		},
		{
			MethodName: "UnaryCall",
			Handler:    _MqttdService_UnaryCall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCall",
			Handler:       _MqttdService_StreamCall_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
