// Code generated by protoc-gen-go. DO NOT EDIT.
// source: list_for_user.proto

package camerad

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/mwitkow/go-proto-validators"
	camera "github.com/nayotta/metathings/pkg/proto/camera"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListForUserRequest struct {
	Name                 *wrappers.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CoreId               *wrappers.StringValue `protobuf:"bytes,2,opt,name=core_id,json=coreId,proto3" json:"core_id,omitempty"`
	EntityName           *wrappers.StringValue `protobuf:"bytes,3,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	State                camera.CameraState    `protobuf:"varint,4,opt,name=state,proto3,enum=ai.metathings.service.camera.CameraState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListForUserRequest) Reset()         { *m = ListForUserRequest{} }
func (m *ListForUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListForUserRequest) ProtoMessage()    {}
func (*ListForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eb8008bafc57221, []int{0}
}

func (m *ListForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListForUserRequest.Unmarshal(m, b)
}
func (m *ListForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListForUserRequest.Marshal(b, m, deterministic)
}
func (m *ListForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListForUserRequest.Merge(m, src)
}
func (m *ListForUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListForUserRequest.Size(m)
}
func (m *ListForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListForUserRequest proto.InternalMessageInfo

func (m *ListForUserRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ListForUserRequest) GetCoreId() *wrappers.StringValue {
	if m != nil {
		return m.CoreId
	}
	return nil
}

func (m *ListForUserRequest) GetEntityName() *wrappers.StringValue {
	if m != nil {
		return m.EntityName
	}
	return nil
}

func (m *ListForUserRequest) GetState() camera.CameraState {
	if m != nil {
		return m.State
	}
	return camera.CameraState_CAMERA_STATE_UNKNOWN
}

type ListForUserResponse struct {
	Cameras              []*Camera `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListForUserResponse) Reset()         { *m = ListForUserResponse{} }
func (m *ListForUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListForUserResponse) ProtoMessage()    {}
func (*ListForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eb8008bafc57221, []int{1}
}

func (m *ListForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListForUserResponse.Unmarshal(m, b)
}
func (m *ListForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListForUserResponse.Marshal(b, m, deterministic)
}
func (m *ListForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListForUserResponse.Merge(m, src)
}
func (m *ListForUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListForUserResponse.Size(m)
}
func (m *ListForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListForUserResponse proto.InternalMessageInfo

func (m *ListForUserResponse) GetCameras() []*Camera {
	if m != nil {
		return m.Cameras
	}
	return nil
}

func init() {
	proto.RegisterType((*ListForUserRequest)(nil), "ai.metathings.service.camerad.ListForUserRequest")
	proto.RegisterType((*ListForUserResponse)(nil), "ai.metathings.service.camerad.ListForUserResponse")
}

func init() { proto.RegisterFile("list_for_user.proto", fileDescriptor_7eb8008bafc57221) }

var fileDescriptor_7eb8008bafc57221 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x6b, 0xea, 0x40,
	0x10, 0xc7, 0xc9, 0xd3, 0xa7, 0xb0, 0x3e, 0xde, 0x21, 0x5e, 0x82, 0xb4, 0x45, 0x84, 0x82, 0x3d,
	0xb8, 0x5b, 0x2c, 0xed, 0xa5, 0x94, 0x1e, 0x0a, 0x85, 0x42, 0xe9, 0x21, 0x52, 0xaf, 0x61, 0x4d,
	0xc6, 0x75, 0x31, 0xc9, 0xa6, 0x3b, 0x13, 0xc5, 0x3f, 0xbe, 0x50, 0x92, 0x8d, 0xad, 0xbd, 0x88,
	0xa7, 0xd9, 0x65, 0xe7, 0xf3, 0xfd, 0xc1, 0xb2, 0x7e, 0xaa, 0x91, 0xa2, 0xa5, 0xb1, 0x51, 0x89,
	0x60, 0x79, 0x61, 0x0d, 0x19, 0xff, 0x5c, 0x6a, 0x9e, 0x01, 0x49, 0x5a, 0xe9, 0x5c, 0x21, 0x47,
	0xb0, 0x1b, 0x1d, 0x03, 0x8f, 0x65, 0x06, 0x56, 0x26, 0x83, 0x0b, 0x65, 0x8c, 0x4a, 0x41, 0xd4,
	0xcb, 0x8b, 0x72, 0x29, 0xb6, 0x56, 0x16, 0x05, 0x58, 0x74, 0xf8, 0xe0, 0x4e, 0x69, 0x5a, 0x95,
	0x0b, 0x1e, 0x9b, 0x4c, 0x64, 0x5b, 0x4d, 0x6b, 0xb3, 0x15, 0xca, 0x4c, 0xea, 0xc7, 0xc9, 0x46,
	0xa6, 0x3a, 0x91, 0x64, 0x2c, 0x8a, 0xef, 0x63, 0xc3, 0xdd, 0x1f, 0x70, 0xb9, 0xdc, 0x19, 0x22,
	0x29, 0x7e, 0x62, 0x88, 0x62, 0xad, 0x9c, 0xa5, 0x70, 0x41, 0x9a, 0xd1, 0xc0, 0xff, 0x0e, 0x6f,
	0xa3, 0x4f, 0x8f, 0xf9, 0xaf, 0x1a, 0xe9, 0xd9, 0xd8, 0x77, 0x04, 0x1b, 0xc2, 0x47, 0x09, 0x48,
	0xfe, 0x35, 0x6b, 0xe7, 0x32, 0x83, 0xc0, 0x1b, 0x7a, 0xe3, 0xde, 0xf4, 0x8c, 0xbb, 0x22, 0x7c,
	0x5f, 0x84, 0xcf, 0xc8, 0xea, 0x5c, 0xcd, 0x65, 0x5a, 0x42, 0x58, 0x6f, 0xfa, 0xb7, 0xac, 0x1b,
	0x1b, 0x0b, 0x91, 0x4e, 0x82, 0x3f, 0x27, 0x40, 0x9d, 0x6a, 0xf9, 0x25, 0xf1, 0x1f, 0x58, 0x0f,
	0x72, 0xd2, 0xb4, 0x8b, 0x6a, 0xbf, 0xd6, 0x09, 0x28, 0x73, 0xc0, 0x5b, 0xe5, 0xfa, 0xc8, 0xfe,
	0x22, 0x49, 0x82, 0xa0, 0x3d, 0xf4, 0xc6, 0xff, 0xa7, 0x57, 0xfc, 0xd8, 0x87, 0xf0, 0xa7, 0x7a,
	0xcc, 0x2a, 0x20, 0x74, 0xdc, 0x68, 0xce, 0xfa, 0xbf, 0xea, 0x63, 0x61, 0x72, 0xac, 0x74, 0xbb,
	0x8e, 0xc1, 0xc0, 0x1b, 0xb6, 0xc6, 0xbd, 0xe9, 0xe5, 0x51, 0xe5, 0xa4, 0x91, 0x0e, 0xf7, 0xd4,
	0xa2, 0x53, 0x47, 0xbf, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x66, 0x20, 0xde, 0x06, 0x37, 0x02,
	0x00, 0x00,
}
