// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create_credential.proto

package identityd2

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCredentialRequest struct {
	Credential           *OpCredential        `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	SecretSize           *wrappers.Int32Value `protobuf:"bytes,2,opt,name=secret_size,json=secretSize,proto3" json:"secret_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateCredentialRequest) Reset()         { *m = CreateCredentialRequest{} }
func (m *CreateCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCredentialRequest) ProtoMessage()    {}
func (*CreateCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f34767a917b63eb, []int{0}
}

func (m *CreateCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredentialRequest.Unmarshal(m, b)
}
func (m *CreateCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredentialRequest.Marshal(b, m, deterministic)
}
func (m *CreateCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredentialRequest.Merge(m, src)
}
func (m *CreateCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCredentialRequest.Size(m)
}
func (m *CreateCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredentialRequest proto.InternalMessageInfo

func (m *CreateCredentialRequest) GetCredential() *OpCredential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *CreateCredentialRequest) GetSecretSize() *wrappers.Int32Value {
	if m != nil {
		return m.SecretSize
	}
	return nil
}

type CreateCredentialResponse struct {
	Credential           *Credential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateCredentialResponse) Reset()         { *m = CreateCredentialResponse{} }
func (m *CreateCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCredentialResponse) ProtoMessage()    {}
func (*CreateCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f34767a917b63eb, []int{1}
}

func (m *CreateCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredentialResponse.Unmarshal(m, b)
}
func (m *CreateCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredentialResponse.Marshal(b, m, deterministic)
}
func (m *CreateCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredentialResponse.Merge(m, src)
}
func (m *CreateCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCredentialResponse.Size(m)
}
func (m *CreateCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredentialResponse proto.InternalMessageInfo

func (m *CreateCredentialResponse) GetCredential() *Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateCredentialRequest)(nil), "ai.metathings.service.identityd2.CreateCredentialRequest")
	proto.RegisterType((*CreateCredentialResponse)(nil), "ai.metathings.service.identityd2.CreateCredentialResponse")
}

func init() { proto.RegisterFile("create_credential.proto", fileDescriptor_7f34767a917b63eb) }

var fileDescriptor_7f34767a917b63eb = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x82, 0x22, 0x9b, 0x8b, 0xe4, 0x92, 0x50, 0x41, 0x4a, 0x4f, 0x1e, 0x64, 0x02,
	0xe9, 0xd5, 0x53, 0x7b, 0x12, 0x04, 0x21, 0x82, 0x78, 0x2b, 0xdb, 0xe4, 0x37, 0x5d, 0x48, 0xb3,
	0xeb, 0xee, 0xa4, 0x62, 0x1f, 0xc1, 0xb7, 0xf1, 0xf5, 0x3c, 0x09, 0x9b, 0xd6, 0x06, 0x14, 0x7a,
	0x1b, 0x98, 0x7f, 0xbe, 0xf9, 0x7e, 0x99, 0x94, 0x0e, 0x8a, 0xb1, 0x2c, 0x1d, 0x2a, 0xb4, 0xac,
	0x55, 0x43, 0xd6, 0x19, 0x36, 0xf1, 0x44, 0x69, 0xda, 0x80, 0x15, 0xaf, 0x75, 0x5b, 0x7b, 0xf2,
	0x70, 0x5b, 0x5d, 0x82, 0x74, 0x48, 0xf1, 0x47, 0x95, 0x8f, 0xaf, 0x6b, 0x63, 0xea, 0x06, 0x59,
	0xc8, 0xaf, 0xba, 0xd7, 0xec, 0xdd, 0x29, 0x6b, 0xe1, 0x7c, 0x4f, 0x18, 0x27, 0x5b, 0xd5, 0xe8,
	0x4a, 0x31, 0xb2, 0xc3, 0xb0, 0x5f, 0x44, 0x1b, 0x53, 0x61, 0xff, 0x67, 0xfa, 0x25, 0x64, 0xb2,
	0x08, 0x0e, 0x8b, 0x5f, 0x85, 0x02, 0x6f, 0x1d, 0x3c, 0xc7, 0x2f, 0x52, 0x1e, 0xbd, 0x52, 0x31,
	0x11, 0x37, 0x51, 0x4e, 0x74, 0x4a, 0x8c, 0x1e, 0xed, 0x11, 0x35, 0xbf, 0xf8, 0x9e, 0x9f, 0x7d,
	0x8a, 0xd1, 0xa5, 0x28, 0x06, 0xac, 0xf8, 0x4e, 0x46, 0x1e, 0xa5, 0x03, 0x2f, 0xbd, 0xde, 0x21,
	0x1d, 0x05, 0xf4, 0x15, 0xf5, 0x8d, 0xe8, 0xd0, 0x88, 0xee, 0x5b, 0x9e, 0xe5, 0xcf, 0xaa, 0xe9,
	0x50, 0xc8, 0x3e, 0xff, 0xa4, 0x77, 0x98, 0xae, 0x65, 0xfa, 0x57, 0xd9, 0x5b, 0xd3, 0x7a, 0xc4,
	0x0f, 0xff, 0x38, 0xdf, 0x9e, 0x76, 0x1e, 0x90, 0x06, 0xf7, 0xab, 0xf3, 0xa0, 0x32, 0xfb, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xe2, 0x78, 0xa3, 0x25, 0xa7, 0x01, 0x00, 0x00,
}
