// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: list_groups_for_object.proto

package identityd2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _list_groups_for_object_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ListGroupsForObjectRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListGroupsForObjectRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetObject() == nil {
		return ListGroupsForObjectRequestValidationError{
			field:  "Object",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetObject()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListGroupsForObjectRequestValidationError{
				field:  "Object",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ListGroupsForObjectRequestValidationError is the validation error returned
// by ListGroupsForObjectRequest.Validate if the designated constraints aren't met.
type ListGroupsForObjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListGroupsForObjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListGroupsForObjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListGroupsForObjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListGroupsForObjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListGroupsForObjectRequestValidationError) ErrorName() string {
	return "ListGroupsForObjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListGroupsForObjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListGroupsForObjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListGroupsForObjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListGroupsForObjectRequestValidationError{}

// Validate checks the field values on ListGroupsForObjectResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListGroupsForObjectResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetGroups() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListGroupsForObjectResponseValidationError{
					field:  fmt.Sprintf("Groups[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListGroupsForObjectResponseValidationError is the validation error returned
// by ListGroupsForObjectResponse.Validate if the designated constraints
// aren't met.
type ListGroupsForObjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListGroupsForObjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListGroupsForObjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListGroupsForObjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListGroupsForObjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListGroupsForObjectResponseValidationError) ErrorName() string {
	return "ListGroupsForObjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListGroupsForObjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListGroupsForObjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListGroupsForObjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListGroupsForObjectResponseValidationError{}
