// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: remove_role_from_entity.proto

package identityd2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _remove_role_from_entity_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on RemoveRoleFromEntityRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RemoveRoleFromEntityRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetEntity() == nil {
		return RemoveRoleFromEntityRequestValidationError{
			field:  "Entity",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetEntity()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RemoveRoleFromEntityRequestValidationError{
				field:  "Entity",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetRole() == nil {
		return RemoveRoleFromEntityRequestValidationError{
			field:  "Role",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetRole()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RemoveRoleFromEntityRequestValidationError{
				field:  "Role",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// RemoveRoleFromEntityRequestValidationError is the validation error returned
// by RemoveRoleFromEntityRequest.Validate if the designated constraints
// aren't met.
type RemoveRoleFromEntityRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveRoleFromEntityRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveRoleFromEntityRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveRoleFromEntityRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveRoleFromEntityRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveRoleFromEntityRequestValidationError) ErrorName() string {
	return "RemoveRoleFromEntityRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveRoleFromEntityRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveRoleFromEntityRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveRoleFromEntityRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveRoleFromEntityRequestValidationError{}
