// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pagination.proto

package pagination

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _pagination_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on OpPaginationOption with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *OpPaginationOption) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetPageSize()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OpPaginationOptionValidationError{
				field:  "PageSize",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetPageToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OpPaginationOptionValidationError{
				field:  "PageToken",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// OpPaginationOptionValidationError is the validation error returned by
// OpPaginationOption.Validate if the designated constraints aren't met.
type OpPaginationOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OpPaginationOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OpPaginationOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OpPaginationOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OpPaginationOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OpPaginationOptionValidationError) ErrorName() string {
	return "OpPaginationOptionValidationError"
}

// Error satisfies the builtin error interface
func (e OpPaginationOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOpPaginationOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OpPaginationOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OpPaginationOptionValidationError{}

// Validate checks the field values on PaginationOption with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *PaginationOption) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for NextPageToken

	return nil
}

// PaginationOptionValidationError is the validation error returned by
// PaginationOption.Validate if the designated constraints aren't met.
type PaginationOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationOptionValidationError) ErrorName() string { return "PaginationOptionValidationError" }

// Error satisfies the builtin error interface
func (e PaginationOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaginationOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationOptionValidationError{}
