// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: add_role_to_entity.proto

package identityd2

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AddRoleToEntityRequest) Validate() error {
	if nil == this.Entity {
		return github_com_mwitkow_go_proto_validators.FieldError("Entity", fmt.Errorf("message must exist"))
	}
	if this.Entity != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Entity); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Entity", err)
		}
	}
	if nil == this.Role {
		return github_com_mwitkow_go_proto_validators.FieldError("Role", fmt.Errorf("message must exist"))
	}
	if this.Role != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Role); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Role", err)
		}
	}
	return nil
}
