// Code generated by protoc-gen-go. DO NOT EDIT.
// source: list_actions.proto

package identityd2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListActionsRequest struct {
	Action               *OpAction `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListActionsRequest) Reset()         { *m = ListActionsRequest{} }
func (m *ListActionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListActionsRequest) ProtoMessage()    {}
func (*ListActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f26ddb2c99b463f, []int{0}
}

func (m *ListActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActionsRequest.Unmarshal(m, b)
}
func (m *ListActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActionsRequest.Marshal(b, m, deterministic)
}
func (m *ListActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActionsRequest.Merge(m, src)
}
func (m *ListActionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListActionsRequest.Size(m)
}
func (m *ListActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListActionsRequest proto.InternalMessageInfo

func (m *ListActionsRequest) GetAction() *OpAction {
	if m != nil {
		return m.Action
	}
	return nil
}

type ListActionsResponse struct {
	Actions              []*Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListActionsResponse) Reset()         { *m = ListActionsResponse{} }
func (m *ListActionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListActionsResponse) ProtoMessage()    {}
func (*ListActionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f26ddb2c99b463f, []int{1}
}

func (m *ListActionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActionsResponse.Unmarshal(m, b)
}
func (m *ListActionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActionsResponse.Marshal(b, m, deterministic)
}
func (m *ListActionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActionsResponse.Merge(m, src)
}
func (m *ListActionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListActionsResponse.Size(m)
}
func (m *ListActionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListActionsResponse proto.InternalMessageInfo

func (m *ListActionsResponse) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*ListActionsRequest)(nil), "ai.metathings.service.identityd2.ListActionsRequest")
	proto.RegisterType((*ListActionsResponse)(nil), "ai.metathings.service.identityd2.ListActionsResponse")
}

func init() { proto.RegisterFile("list_actions.proto", fileDescriptor_1f26ddb2c99b463f) }

var fileDescriptor_1f26ddb2c99b463f = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xcf, 0xb1, 0x6a, 0x84, 0x40,
	0x10, 0x06, 0x60, 0x24, 0x60, 0x60, 0xed, 0x36, 0x8d, 0x58, 0x04, 0xb1, 0x92, 0x14, 0x2b, 0x98,
	0x27, 0x88, 0x75, 0x20, 0x60, 0x95, 0x54, 0x61, 0xd5, 0x89, 0x19, 0xd0, 0xdd, 0xbd, 0x9d, 0xf1,
	0x8e, 0x7b, 0xfb, 0x03, 0x77, 0xaf, 0xb8, 0xca, 0x72, 0x60, 0xfe, 0xef, 0x9f, 0x11, 0x72, 0x41,
	0xe2, 0x5f, 0x3d, 0x32, 0x5a, 0x43, 0xca, 0x79, 0xcb, 0x56, 0x96, 0x1a, 0xd5, 0x0a, 0xac, 0xf9,
	0x1f, 0xcd, 0x4c, 0x8a, 0xc0, 0x9f, 0x71, 0x04, 0x85, 0x13, 0x18, 0x46, 0xbe, 0x4e, 0x6d, 0xf1,
	0x3a, 0x5b, 0x3b, 0x2f, 0xd0, 0xec, 0xfb, 0xc3, 0xf6, 0xd7, 0x5c, 0xbc, 0x76, 0x0e, 0x7c, 0x14,
	0x8a, 0x6c, 0xb5, 0x13, 0x2c, 0x61, 0xa8, 0xbe, 0x85, 0xfc, 0x44, 0xe2, 0x8f, 0xd0, 0xd1, 0xc3,
	0x69, 0x03, 0x62, 0xd9, 0x89, 0x34, 0xb4, 0xe6, 0x49, 0x99, 0xd4, 0x59, 0xfb, 0xa6, 0x8e, 0x5a,
	0xd5, 0x97, 0x0b, 0x46, 0x1f, 0x93, 0xd5, 0x8f, 0x78, 0x79, 0x90, 0xc9, 0x59, 0x43, 0x20, 0x3b,
	0xf1, 0x1c, 0x1f, 0xca, 0x93, 0xf2, 0xa9, 0xce, 0xda, 0xfa, 0xd8, 0x8e, 0xf2, 0x3d, 0x38, 0xa4,
	0xfb, 0xed, 0xef, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x3f, 0x88, 0xe6, 0x20, 0x01, 0x00,
	0x00,
}
