/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ai.metathings.service.identityd2.OpGroup');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.ai.metathings.service.identityd2.OpDomain');
goog.require('proto.ai.metathings.service.identityd2.OpEntity');
goog.require('proto.ai.metathings.service.identityd2.OpRole');
goog.require('proto.google.protobuf.StringValue');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.identityd2.OpGroup = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ai.metathings.service.identityd2.OpGroup.repeatedFields_, null);
};
goog.inherits(proto.ai.metathings.service.identityd2.OpGroup, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.identityd2.OpGroup.displayName = 'proto.ai.metathings.service.identityd2.OpGroup';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ai.metathings.service.identityd2.OpGroup.repeatedFields_ = [3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.identityd2.OpGroup.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.identityd2.OpGroup} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.identityd2.OpGroup.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    domain: (f = msg.getDomain()) && proto.ai.metathings.service.identityd2.OpDomain.toObject(includeInstance, f),
    rolesList: jspb.Message.toObjectList(msg.getRolesList(),
    proto.ai.metathings.service.identityd2.OpRole.toObject, includeInstance),
    subjectsList: jspb.Message.toObjectList(msg.getSubjectsList(),
    proto.ai.metathings.service.identityd2.OpEntity.toObject, includeInstance),
    objectsList: jspb.Message.toObjectList(msg.getObjectsList(),
    proto.ai.metathings.service.identityd2.OpEntity.toObject, includeInstance),
    name: (f = msg.getName()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    alias: (f = msg.getAlias()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    description: (f = msg.getDescription()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    extraMap: (f = msg.getExtraMap()) ? f.toObject(includeInstance, proto.google.protobuf.StringValue.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.identityd2.OpGroup}
 */
proto.ai.metathings.service.identityd2.OpGroup.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.identityd2.OpGroup;
  return proto.ai.metathings.service.identityd2.OpGroup.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.identityd2.OpGroup} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.identityd2.OpGroup}
 */
proto.ai.metathings.service.identityd2.OpGroup.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto.ai.metathings.service.identityd2.OpDomain;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpDomain.deserializeBinaryFromReader);
      msg.setDomain(value);
      break;
    case 3:
      var value = new proto.ai.metathings.service.identityd2.OpRole;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpRole.deserializeBinaryFromReader);
      msg.addRoles(value);
      break;
    case 4:
      var value = new proto.ai.metathings.service.identityd2.OpEntity;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpEntity.deserializeBinaryFromReader);
      msg.addSubjects(value);
      break;
    case 5:
      var value = new proto.ai.metathings.service.identityd2.OpEntity;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpEntity.deserializeBinaryFromReader);
      msg.addObjects(value);
      break;
    case 6:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setName(value);
      break;
    case 7:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setAlias(value);
      break;
    case 8:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setDescription(value);
      break;
    case 9:
      var value = msg.getExtraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.StringValue.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.identityd2.OpGroup.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.identityd2.OpGroup} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.identityd2.OpGroup.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getDomain();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ai.metathings.service.identityd2.OpDomain.serializeBinaryToWriter
    );
  }
  f = message.getRolesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.ai.metathings.service.identityd2.OpRole.serializeBinaryToWriter
    );
  }
  f = message.getSubjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.ai.metathings.service.identityd2.OpEntity.serializeBinaryToWriter
    );
  }
  f = message.getObjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.ai.metathings.service.identityd2.OpEntity.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getAlias();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getDescription();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getExtraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(9, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.StringValue.serializeBinaryToWriter);
  }
};


/**
 * optional google.protobuf.StringValue id = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 1));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.identityd2.OpGroup.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional OpDomain domain = 2;
 * @return {?proto.ai.metathings.service.identityd2.OpDomain}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getDomain = function() {
  return /** @type{?proto.ai.metathings.service.identityd2.OpDomain} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.identityd2.OpDomain, 2));
};


/** @param {?proto.ai.metathings.service.identityd2.OpDomain|undefined} value */
proto.ai.metathings.service.identityd2.OpGroup.prototype.setDomain = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearDomain = function() {
  this.setDomain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.hasDomain = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated OpRole roles = 3;
 * @return {!Array<!proto.ai.metathings.service.identityd2.OpRole>}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getRolesList = function() {
  return /** @type{!Array<!proto.ai.metathings.service.identityd2.OpRole>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ai.metathings.service.identityd2.OpRole, 3));
};


/** @param {!Array<!proto.ai.metathings.service.identityd2.OpRole>} value */
proto.ai.metathings.service.identityd2.OpGroup.prototype.setRolesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.ai.metathings.service.identityd2.OpRole=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ai.metathings.service.identityd2.OpRole}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.addRoles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.ai.metathings.service.identityd2.OpRole, opt_index);
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearRolesList = function() {
  this.setRolesList([]);
};


/**
 * repeated OpEntity subjects = 4;
 * @return {!Array<!proto.ai.metathings.service.identityd2.OpEntity>}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getSubjectsList = function() {
  return /** @type{!Array<!proto.ai.metathings.service.identityd2.OpEntity>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ai.metathings.service.identityd2.OpEntity, 4));
};


/** @param {!Array<!proto.ai.metathings.service.identityd2.OpEntity>} value */
proto.ai.metathings.service.identityd2.OpGroup.prototype.setSubjectsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ai.metathings.service.identityd2.OpEntity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ai.metathings.service.identityd2.OpEntity}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.addSubjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ai.metathings.service.identityd2.OpEntity, opt_index);
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearSubjectsList = function() {
  this.setSubjectsList([]);
};


/**
 * repeated OpEntity objects = 5;
 * @return {!Array<!proto.ai.metathings.service.identityd2.OpEntity>}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getObjectsList = function() {
  return /** @type{!Array<!proto.ai.metathings.service.identityd2.OpEntity>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ai.metathings.service.identityd2.OpEntity, 5));
};


/** @param {!Array<!proto.ai.metathings.service.identityd2.OpEntity>} value */
proto.ai.metathings.service.identityd2.OpGroup.prototype.setObjectsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.ai.metathings.service.identityd2.OpEntity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ai.metathings.service.identityd2.OpEntity}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.addObjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.ai.metathings.service.identityd2.OpEntity, opt_index);
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearObjectsList = function() {
  this.setObjectsList([]);
};


/**
 * optional google.protobuf.StringValue name = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 6));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.identityd2.OpGroup.prototype.setName = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearName = function() {
  this.setName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.hasName = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.StringValue alias = 7;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getAlias = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 7));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.identityd2.OpGroup.prototype.setAlias = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearAlias = function() {
  this.setAlias(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.hasAlias = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.StringValue description = 8;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getDescription = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 8));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.identityd2.OpGroup.prototype.setDescription = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearDescription = function() {
  this.setDescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * map<string, google.protobuf.StringValue> extra = 9;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.StringValue>}
 */
proto.ai.metathings.service.identityd2.OpGroup.prototype.getExtraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.StringValue>} */ (
      jspb.Message.getMapField(this, 9, opt_noLazyCreate,
      proto.google.protobuf.StringValue));
};


proto.ai.metathings.service.identityd2.OpGroup.prototype.clearExtraMap = function() {
  this.getExtraMap().clear();
};


