/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ai.metathings.service.identityd2.OpToken');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ai.metathings.service.identityd2.OpCredential');
goog.require('proto.ai.metathings.service.identityd2.OpDomain');
goog.require('proto.ai.metathings.service.identityd2.OpEntity');
goog.require('proto.ai.metathings.service.identityd2.OpGroup');
goog.require('proto.ai.metathings.service.identityd2.OpRole');
goog.require('proto.google.protobuf.StringValue');
goog.require('proto.google.protobuf.Timestamp');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.metathings.service.identityd2.OpToken = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ai.metathings.service.identityd2.OpToken.repeatedFields_, null);
};
goog.inherits(proto.ai.metathings.service.identityd2.OpToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.metathings.service.identityd2.OpToken.displayName = 'proto.ai.metathings.service.identityd2.OpToken';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ai.metathings.service.identityd2.OpToken.repeatedFields_ = [5,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.metathings.service.identityd2.OpToken.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.metathings.service.identityd2.OpToken} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.identityd2.OpToken.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    issuedAt: (f = msg.getIssuedAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    expiresAt: (f = msg.getExpiresAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    entity: (f = msg.getEntity()) && proto.ai.metathings.service.identityd2.OpEntity.toObject(includeInstance, f),
    rolesList: jspb.Message.toObjectList(msg.getRolesList(),
    proto.ai.metathings.service.identityd2.OpRole.toObject, includeInstance),
    domain: (f = msg.getDomain()) && proto.ai.metathings.service.identityd2.OpDomain.toObject(includeInstance, f),
    credential: (f = msg.getCredential()) && proto.ai.metathings.service.identityd2.OpCredential.toObject(includeInstance, f),
    text: (f = msg.getText()) && proto.google.protobuf.StringValue.toObject(includeInstance, f),
    groupsList: jspb.Message.toObjectList(msg.getGroupsList(),
    proto.ai.metathings.service.identityd2.OpGroup.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.metathings.service.identityd2.OpToken}
 */
proto.ai.metathings.service.identityd2.OpToken.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.metathings.service.identityd2.OpToken;
  return proto.ai.metathings.service.identityd2.OpToken.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.metathings.service.identityd2.OpToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.metathings.service.identityd2.OpToken}
 */
proto.ai.metathings.service.identityd2.OpToken.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setIssuedAt(value);
      break;
    case 3:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setExpiresAt(value);
      break;
    case 4:
      var value = new proto.ai.metathings.service.identityd2.OpEntity;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpEntity.deserializeBinaryFromReader);
      msg.setEntity(value);
      break;
    case 5:
      var value = new proto.ai.metathings.service.identityd2.OpRole;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpRole.deserializeBinaryFromReader);
      msg.addRoles(value);
      break;
    case 6:
      var value = new proto.ai.metathings.service.identityd2.OpDomain;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpDomain.deserializeBinaryFromReader);
      msg.setDomain(value);
      break;
    case 7:
      var value = new proto.ai.metathings.service.identityd2.OpCredential;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpCredential.deserializeBinaryFromReader);
      msg.setCredential(value);
      break;
    case 8:
      var value = new proto.google.protobuf.StringValue;
      reader.readMessage(value,proto.google.protobuf.StringValue.deserializeBinaryFromReader);
      msg.setText(value);
      break;
    case 9:
      var value = new proto.ai.metathings.service.identityd2.OpGroup;
      reader.readMessage(value,proto.ai.metathings.service.identityd2.OpGroup.deserializeBinaryFromReader);
      msg.addGroups(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.metathings.service.identityd2.OpToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.metathings.service.identityd2.OpToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.metathings.service.identityd2.OpToken.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getIssuedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getExpiresAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEntity();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.ai.metathings.service.identityd2.OpEntity.serializeBinaryToWriter
    );
  }
  f = message.getRolesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.ai.metathings.service.identityd2.OpRole.serializeBinaryToWriter
    );
  }
  f = message.getDomain();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.ai.metathings.service.identityd2.OpDomain.serializeBinaryToWriter
    );
  }
  f = message.getCredential();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.ai.metathings.service.identityd2.OpCredential.serializeBinaryToWriter
    );
  }
  f = message.getText();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.google.protobuf.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getGroupsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.ai.metathings.service.identityd2.OpGroup.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue id = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 1));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp issued_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getIssuedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setIssuedAt = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearIssuedAt = function() {
  this.setIssuedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.hasIssuedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp expires_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getExpiresAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 3));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setExpiresAt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearExpiresAt = function() {
  this.setExpiresAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.hasExpiresAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional OpEntity entity = 4;
 * @return {?proto.ai.metathings.service.identityd2.OpEntity}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getEntity = function() {
  return /** @type{?proto.ai.metathings.service.identityd2.OpEntity} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.identityd2.OpEntity, 4));
};


/** @param {?proto.ai.metathings.service.identityd2.OpEntity|undefined} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setEntity = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearEntity = function() {
  this.setEntity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.hasEntity = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated OpRole roles = 5;
 * @return {!Array<!proto.ai.metathings.service.identityd2.OpRole>}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getRolesList = function() {
  return /** @type{!Array<!proto.ai.metathings.service.identityd2.OpRole>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ai.metathings.service.identityd2.OpRole, 5));
};


/** @param {!Array<!proto.ai.metathings.service.identityd2.OpRole>} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setRolesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.ai.metathings.service.identityd2.OpRole=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ai.metathings.service.identityd2.OpRole}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.addRoles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.ai.metathings.service.identityd2.OpRole, opt_index);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearRolesList = function() {
  this.setRolesList([]);
};


/**
 * optional OpDomain domain = 6;
 * @return {?proto.ai.metathings.service.identityd2.OpDomain}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getDomain = function() {
  return /** @type{?proto.ai.metathings.service.identityd2.OpDomain} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.identityd2.OpDomain, 6));
};


/** @param {?proto.ai.metathings.service.identityd2.OpDomain|undefined} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setDomain = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearDomain = function() {
  this.setDomain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.hasDomain = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional OpCredential credential = 7;
 * @return {?proto.ai.metathings.service.identityd2.OpCredential}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getCredential = function() {
  return /** @type{?proto.ai.metathings.service.identityd2.OpCredential} */ (
    jspb.Message.getWrapperField(this, proto.ai.metathings.service.identityd2.OpCredential, 7));
};


/** @param {?proto.ai.metathings.service.identityd2.OpCredential|undefined} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setCredential = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearCredential = function() {
  this.setCredential(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.hasCredential = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.StringValue text = 8;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getText = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.StringValue, 8));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setText = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearText = function() {
  this.setText(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.hasText = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated OpGroup groups = 9;
 * @return {!Array<!proto.ai.metathings.service.identityd2.OpGroup>}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.getGroupsList = function() {
  return /** @type{!Array<!proto.ai.metathings.service.identityd2.OpGroup>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ai.metathings.service.identityd2.OpGroup, 9));
};


/** @param {!Array<!proto.ai.metathings.service.identityd2.OpGroup>} value */
proto.ai.metathings.service.identityd2.OpToken.prototype.setGroupsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.ai.metathings.service.identityd2.OpGroup=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ai.metathings.service.identityd2.OpGroup}
 */
proto.ai.metathings.service.identityd2.OpToken.prototype.addGroups = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.ai.metathings.service.identityd2.OpGroup, opt_index);
};


proto.ai.metathings.service.identityd2.OpToken.prototype.clearGroupsList = function() {
  this.setGroupsList([]);
};


