// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: patch_credential.proto

package identityd2

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PatchCredentialRequest) Validate() error {
	if nil == this.Id {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf("message must exist"))
	}
	if this.Id != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Id); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Id", err)
		}
	}
	if this.Alias != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Alias); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Alias", err)
		}
	}
	if this.Description != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Description); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Description", err)
		}
	}
	return nil
}
func (this *PatchCredentialResponse) Validate() error {
	if this.Credential != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Credential); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Credential", err)
		}
	}
	return nil
}
