// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream_call.proto

package component

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamCallRequest struct {
	// Types that are valid to be assigned to Request:
	//	*StreamCallRequest_Config
	//	*StreamCallRequest_Data
	Request              isStreamCallRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *StreamCallRequest) Reset()         { *m = StreamCallRequest{} }
func (m *StreamCallRequest) String() string { return proto.CompactTextString(m) }
func (*StreamCallRequest) ProtoMessage()    {}
func (*StreamCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c43dc63f14d203, []int{0}
}

func (m *StreamCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamCallRequest.Unmarshal(m, b)
}
func (m *StreamCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamCallRequest.Marshal(b, m, deterministic)
}
func (m *StreamCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCallRequest.Merge(m, src)
}
func (m *StreamCallRequest) XXX_Size() int {
	return xxx_messageInfo_StreamCallRequest.Size(m)
}
func (m *StreamCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCallRequest proto.InternalMessageInfo

type isStreamCallRequest_Request interface {
	isStreamCallRequest_Request()
}

type StreamCallRequest_Config struct {
	Config *StreamCallConfigRequest `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type StreamCallRequest_Data struct {
	Data *StreamCallDataRequest `protobuf:"bytes,21,opt,name=data,proto3,oneof"`
}

func (*StreamCallRequest_Config) isStreamCallRequest_Request() {}

func (*StreamCallRequest_Data) isStreamCallRequest_Request() {}

func (m *StreamCallRequest) GetRequest() isStreamCallRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *StreamCallRequest) GetConfig() *StreamCallConfigRequest {
	if x, ok := m.GetRequest().(*StreamCallRequest_Config); ok {
		return x.Config
	}
	return nil
}

func (m *StreamCallRequest) GetData() *StreamCallDataRequest {
	if x, ok := m.GetRequest().(*StreamCallRequest_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamCallRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamCallRequest_Config)(nil),
		(*StreamCallRequest_Data)(nil),
	}
}

type StreamCallConfigRequest struct {
	Method               *wrappers.StringValue `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StreamCallConfigRequest) Reset()         { *m = StreamCallConfigRequest{} }
func (m *StreamCallConfigRequest) String() string { return proto.CompactTextString(m) }
func (*StreamCallConfigRequest) ProtoMessage()    {}
func (*StreamCallConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c43dc63f14d203, []int{1}
}

func (m *StreamCallConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamCallConfigRequest.Unmarshal(m, b)
}
func (m *StreamCallConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamCallConfigRequest.Marshal(b, m, deterministic)
}
func (m *StreamCallConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCallConfigRequest.Merge(m, src)
}
func (m *StreamCallConfigRequest) XXX_Size() int {
	return xxx_messageInfo_StreamCallConfigRequest.Size(m)
}
func (m *StreamCallConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCallConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCallConfigRequest proto.InternalMessageInfo

func (m *StreamCallConfigRequest) GetMethod() *wrappers.StringValue {
	if m != nil {
		return m.Method
	}
	return nil
}

type StreamCallDataRequest struct {
	Value                *any.Any `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamCallDataRequest) Reset()         { *m = StreamCallDataRequest{} }
func (m *StreamCallDataRequest) String() string { return proto.CompactTextString(m) }
func (*StreamCallDataRequest) ProtoMessage()    {}
func (*StreamCallDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c43dc63f14d203, []int{2}
}

func (m *StreamCallDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamCallDataRequest.Unmarshal(m, b)
}
func (m *StreamCallDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamCallDataRequest.Marshal(b, m, deterministic)
}
func (m *StreamCallDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCallDataRequest.Merge(m, src)
}
func (m *StreamCallDataRequest) XXX_Size() int {
	return xxx_messageInfo_StreamCallDataRequest.Size(m)
}
func (m *StreamCallDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCallDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCallDataRequest proto.InternalMessageInfo

func (m *StreamCallDataRequest) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type StreamCallResponse struct {
	// Types that are valid to be assigned to Response:
	//	*StreamCallResponse_Config
	//	*StreamCallResponse_Data
	Response             isStreamCallResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *StreamCallResponse) Reset()         { *m = StreamCallResponse{} }
func (m *StreamCallResponse) String() string { return proto.CompactTextString(m) }
func (*StreamCallResponse) ProtoMessage()    {}
func (*StreamCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c43dc63f14d203, []int{3}
}

func (m *StreamCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamCallResponse.Unmarshal(m, b)
}
func (m *StreamCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamCallResponse.Marshal(b, m, deterministic)
}
func (m *StreamCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCallResponse.Merge(m, src)
}
func (m *StreamCallResponse) XXX_Size() int {
	return xxx_messageInfo_StreamCallResponse.Size(m)
}
func (m *StreamCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCallResponse proto.InternalMessageInfo

type isStreamCallResponse_Response interface {
	isStreamCallResponse_Response()
}

type StreamCallResponse_Config struct {
	Config *StreamCallConfigResponse `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type StreamCallResponse_Data struct {
	Data *StreamCallDataResponse `protobuf:"bytes,21,opt,name=data,proto3,oneof"`
}

func (*StreamCallResponse_Config) isStreamCallResponse_Response() {}

func (*StreamCallResponse_Data) isStreamCallResponse_Response() {}

func (m *StreamCallResponse) GetResponse() isStreamCallResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *StreamCallResponse) GetConfig() *StreamCallConfigResponse {
	if x, ok := m.GetResponse().(*StreamCallResponse_Config); ok {
		return x.Config
	}
	return nil
}

func (m *StreamCallResponse) GetData() *StreamCallDataResponse {
	if x, ok := m.GetResponse().(*StreamCallResponse_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamCallResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamCallResponse_Config)(nil),
		(*StreamCallResponse_Data)(nil),
	}
}

type StreamCallConfigResponse struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamCallConfigResponse) Reset()         { *m = StreamCallConfigResponse{} }
func (m *StreamCallConfigResponse) String() string { return proto.CompactTextString(m) }
func (*StreamCallConfigResponse) ProtoMessage()    {}
func (*StreamCallConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c43dc63f14d203, []int{4}
}

func (m *StreamCallConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamCallConfigResponse.Unmarshal(m, b)
}
func (m *StreamCallConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamCallConfigResponse.Marshal(b, m, deterministic)
}
func (m *StreamCallConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCallConfigResponse.Merge(m, src)
}
func (m *StreamCallConfigResponse) XXX_Size() int {
	return xxx_messageInfo_StreamCallConfigResponse.Size(m)
}
func (m *StreamCallConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCallConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCallConfigResponse proto.InternalMessageInfo

func (m *StreamCallConfigResponse) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type StreamCallDataResponse struct {
	Value                *any.Any `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamCallDataResponse) Reset()         { *m = StreamCallDataResponse{} }
func (m *StreamCallDataResponse) String() string { return proto.CompactTextString(m) }
func (*StreamCallDataResponse) ProtoMessage()    {}
func (*StreamCallDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c43dc63f14d203, []int{5}
}

func (m *StreamCallDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamCallDataResponse.Unmarshal(m, b)
}
func (m *StreamCallDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamCallDataResponse.Marshal(b, m, deterministic)
}
func (m *StreamCallDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCallDataResponse.Merge(m, src)
}
func (m *StreamCallDataResponse) XXX_Size() int {
	return xxx_messageInfo_StreamCallDataResponse.Size(m)
}
func (m *StreamCallDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCallDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCallDataResponse proto.InternalMessageInfo

func (m *StreamCallDataResponse) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamCallRequest)(nil), "ai.metathings.component.StreamCallRequest")
	proto.RegisterType((*StreamCallConfigRequest)(nil), "ai.metathings.component.StreamCallConfigRequest")
	proto.RegisterType((*StreamCallDataRequest)(nil), "ai.metathings.component.StreamCallDataRequest")
	proto.RegisterType((*StreamCallResponse)(nil), "ai.metathings.component.StreamCallResponse")
	proto.RegisterType((*StreamCallConfigResponse)(nil), "ai.metathings.component.StreamCallConfigResponse")
	proto.RegisterType((*StreamCallDataResponse)(nil), "ai.metathings.component.StreamCallDataResponse")
}

func init() { proto.RegisterFile("stream_call.proto", fileDescriptor_61c43dc63f14d203) }

var fileDescriptor_61c43dc63f14d203 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0xbf, 0x7c, 0x68, 0xb4, 0xa7, 0xab, 0x0e, 0xf6, 0xc7, 0x22, 0x5a, 0xb2, 0x12, 0xa1,
	0x13, 0xad, 0xe0, 0xca, 0x8d, 0x6d, 0x05, 0xb1, 0xbb, 0x0a, 0x0a, 0x6e, 0xe4, 0xb4, 0x9d, 0xa6,
	0xc1, 0x64, 0x26, 0x26, 0x93, 0x96, 0xde, 0x95, 0x0b, 0xef, 0x47, 0xf0, 0x4a, 0xa4, 0x33, 0x63,
	0xfa, 0x63, 0x0b, 0x75, 0x37, 0xcc, 0x39, 0xef, 0x73, 0x5e, 0x1e, 0x28, 0x24, 0x32, 0x66, 0x18,
	0xbe, 0xf4, 0x31, 0x08, 0x68, 0x14, 0x0b, 0x29, 0x48, 0x19, 0x7d, 0x1a, 0x32, 0x89, 0x72, 0xe4,
	0x73, 0x2f, 0xa1, 0x7d, 0x11, 0x46, 0x82, 0x33, 0x2e, 0xab, 0xc7, 0x9e, 0x10, 0x5e, 0xc0, 0x5c,
	0xb5, 0xd6, 0x4b, 0x87, 0xee, 0x24, 0xc6, 0x28, 0x62, 0x71, 0xa2, 0x83, 0xd5, 0xc3, 0xd5, 0x39,
	0xf2, 0xa9, 0x19, 0x5d, 0x79, 0xbe, 0x1c, 0xa5, 0xbd, 0x19, 0xcc, 0x0d, 0x27, 0xbe, 0x7c, 0x15,
	0x13, 0xd7, 0x13, 0x75, 0x35, 0xac, 0x8f, 0x31, 0xf0, 0x07, 0x28, 0x45, 0x9c, 0xb8, 0xd9, 0x53,
	0xe7, 0x9c, 0x77, 0x0b, 0x0a, 0x0f, 0xaa, 0x61, 0x0b, 0x83, 0xa0, 0xcb, 0xde, 0x52, 0x96, 0x48,
	0x72, 0x0f, 0x76, 0x5f, 0xf0, 0xa1, 0xef, 0x55, 0xac, 0x9a, 0x75, 0x9a, 0x6f, 0x9c, 0xd3, 0x0d,
	0x95, 0xe9, 0x3c, 0xdb, 0x52, 0x01, 0x43, 0xb8, 0xfb, 0xd7, 0x35, 0x04, 0xd2, 0x86, 0x9d, 0x01,
	0x4a, 0xac, 0x14, 0x15, 0x89, 0x6e, 0x41, 0x6a, 0xa3, 0xc4, 0x39, 0x47, 0xa5, 0x9b, 0x39, 0xd8,
	0x8b, 0xf5, 0x97, 0xf3, 0x04, 0xe5, 0x0d, 0x57, 0xc9, 0x35, 0xd8, 0x21, 0x93, 0x23, 0x31, 0x30,
	0xbd, 0x8f, 0xa8, 0x36, 0x46, 0x7f, 0x8c, 0xcd, 0xae, 0xf8, 0xdc, 0x7b, 0xc4, 0x20, 0x65, 0x4d,
	0xfb, 0xeb, 0xf3, 0xe4, 0x7f, 0xcd, 0xea, 0x9a, 0x8c, 0xd3, 0x81, 0xe2, 0xda, 0x12, 0xa4, 0x01,
	0xbb, 0xe3, 0x59, 0xc2, 0x50, 0x0f, 0x7e, 0x51, 0x6f, 0xf8, 0x34, 0xa3, 0xe9, 0x55, 0xe7, 0xc3,
	0x02, 0xb2, 0x28, 0x36, 0x89, 0x04, 0x4f, 0x18, 0xe9, 0xac, 0x98, 0xbd, 0xf8, 0x83, 0x59, 0x8d,
	0x58, 0x50, 0x7b, 0xbb, 0xa4, 0xd6, 0xdd, 0x5a, 0x6d, 0x06, 0xd2, 0x6e, 0x01, 0xf6, 0x63, 0xf3,
	0xe7, 0x34, 0xa0, 0xb2, 0xe9, 0x30, 0x29, 0x2d, 0xd9, 0xcd, 0x65, 0xde, 0xda, 0x50, 0x5a, 0x7f,
	0x81, 0x9c, 0x6d, 0x21, 0xce, 0x08, 0x6b, 0xe6, 0x9f, 0x73, 0x59, 0xe3, 0x9e, 0xad, 0x36, 0x2e,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x73, 0x06, 0x33, 0x3e, 0x03, 0x00, 0x00,
}
