// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_project.proto

package identity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetProjectRequest struct {
	ProjectId            *wrappers.StringValue `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetProjectRequest) Reset()         { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()    {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_project_0861279976f551c6, []int{0}
}
func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (dst *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(dst, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetProjectId() *wrappers.StringValue {
	if m != nil {
		return m.ProjectId
	}
	return nil
}

type GetProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectResponse) Reset()         { *m = GetProjectResponse{} }
func (m *GetProjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectResponse) ProtoMessage()    {}
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_project_0861279976f551c6, []int{1}
}
func (m *GetProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectResponse.Unmarshal(m, b)
}
func (m *GetProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectResponse.Marshal(b, m, deterministic)
}
func (dst *GetProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectResponse.Merge(dst, src)
}
func (m *GetProjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectResponse.Size(m)
}
func (m *GetProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectResponse proto.InternalMessageInfo

func (m *GetProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProjectRequest)(nil), "ai.metathings.service.identity.GetProjectRequest")
	proto.RegisterType((*GetProjectResponse)(nil), "ai.metathings.service.identity.GetProjectResponse")
}

func init() { proto.RegisterFile("get_project.proto", fileDescriptor_get_project_0861279976f551c6) }

var fileDescriptor_get_project_0861279976f551c6 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0x89, 0xc5, 0x89, 0x2b, 0x16, 0x97, 0x4a, 0x0e, 0x39, 0x8f, 0x6b, 0xb4, 0xb9, 0x59,
	0x50, 0xb0, 0x57, 0x0b, 0xb1, 0x93, 0x13, 0xd4, 0xee, 0xd8, 0x24, 0xe3, 0xde, 0x68, 0x92, 0x59,
	0x77, 0x27, 0x09, 0x3e, 0xad, 0xe0, 0x93, 0x08, 0xc9, 0x46, 0xb4, 0xb9, 0x6e, 0x98, 0xf9, 0xbf,
	0x9f, 0x8f, 0x51, 0x53, 0x8b, 0xb2, 0x71, 0x9e, 0xdf, 0x30, 0x17, 0x70, 0x9e, 0x85, 0xd3, 0xb9,
	0x21, 0xa8, 0x50, 0x8c, 0x6c, 0xa9, 0xb6, 0x01, 0x02, 0xfa, 0x96, 0x72, 0x04, 0x2a, 0xb0, 0x16,
	0x92, 0xcf, 0xd9, 0xdc, 0x32, 0xdb, 0x12, 0x75, 0x9f, 0xce, 0x9a, 0x57, 0xdd, 0x79, 0xe3, 0x1c,
	0xfa, 0x30, 0xf0, 0xb3, 0x2b, 0x4b, 0xb2, 0x6d, 0x32, 0xc8, 0xb9, 0xd2, 0x55, 0x47, 0xf2, 0xce,
	0x9d, 0xb6, 0xbc, 0xea, 0x8f, 0xab, 0xd6, 0x94, 0x54, 0x18, 0x61, 0x1f, 0xf4, 0xef, 0x18, 0xb9,
	0xa3, 0x7f, 0x1a, 0xcb, 0x17, 0x35, 0xbd, 0x43, 0x79, 0x18, 0x76, 0x6b, 0xfc, 0x68, 0x30, 0x48,
	0x7a, 0xab, 0x54, 0x4c, 0x6d, 0xa8, 0x38, 0x4e, 0x16, 0xc9, 0xf9, 0xe1, 0xc5, 0x09, 0x0c, 0x42,
	0x30, 0x0a, 0xc1, 0xa3, 0x78, 0xaa, 0xed, 0x93, 0x29, 0x1b, 0xbc, 0x99, 0x7c, 0x7f, 0x9d, 0xee,
	0x2d, 0x92, 0xf5, 0x41, 0xe4, 0xee, 0x8b, 0xe5, 0xb3, 0x4a, 0xff, 0x36, 0x07, 0xc7, 0x75, 0xc0,
	0xf4, 0x5a, 0xed, 0xc7, 0x48, 0xec, 0x3d, 0x83, 0xdd, 0x8f, 0x80, 0xb1, 0x61, 0xe4, 0xb2, 0x49,
	0x6f, 0x70, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x86, 0xcd, 0xe8, 0xf4, 0x55, 0x01, 0x00, 0x00,
}
