// Code generated by protoc-gen-go. DO NOT EDIT.
// source: patch_core.proto

package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"
import state "github.com/nayotta/metathings/pkg/proto/common/state"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PatchCoreRequest struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	State                state.CoreState       `protobuf:"varint,3,opt,name=state,enum=ai.metathings.state.CoreState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PatchCoreRequest) Reset()         { *m = PatchCoreRequest{} }
func (m *PatchCoreRequest) String() string { return proto.CompactTextString(m) }
func (*PatchCoreRequest) ProtoMessage()    {}
func (*PatchCoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_patch_core_8c48faa97cb34ef8, []int{0}
}
func (m *PatchCoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchCoreRequest.Unmarshal(m, b)
}
func (m *PatchCoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchCoreRequest.Marshal(b, m, deterministic)
}
func (dst *PatchCoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchCoreRequest.Merge(dst, src)
}
func (m *PatchCoreRequest) XXX_Size() int {
	return xxx_messageInfo_PatchCoreRequest.Size(m)
}
func (m *PatchCoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchCoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchCoreRequest proto.InternalMessageInfo

func (m *PatchCoreRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PatchCoreRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *PatchCoreRequest) GetState() state.CoreState {
	if m != nil {
		return m.State
	}
	return state.CoreState_CORE_STATE_UNKNOWN
}

type PatchCoreResponse struct {
	Core                 *Core    `protobuf:"bytes,1,opt,name=core" json:"core,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchCoreResponse) Reset()         { *m = PatchCoreResponse{} }
func (m *PatchCoreResponse) String() string { return proto.CompactTextString(m) }
func (*PatchCoreResponse) ProtoMessage()    {}
func (*PatchCoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_patch_core_8c48faa97cb34ef8, []int{1}
}
func (m *PatchCoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchCoreResponse.Unmarshal(m, b)
}
func (m *PatchCoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchCoreResponse.Marshal(b, m, deterministic)
}
func (dst *PatchCoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchCoreResponse.Merge(dst, src)
}
func (m *PatchCoreResponse) XXX_Size() int {
	return xxx_messageInfo_PatchCoreResponse.Size(m)
}
func (m *PatchCoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchCoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PatchCoreResponse proto.InternalMessageInfo

func (m *PatchCoreResponse) GetCore() *Core {
	if m != nil {
		return m.Core
	}
	return nil
}

func init() {
	proto.RegisterType((*PatchCoreRequest)(nil), "ai.metathings.service.core.PatchCoreRequest")
	proto.RegisterType((*PatchCoreResponse)(nil), "ai.metathings.service.core.PatchCoreResponse")
}

func init() { proto.RegisterFile("patch_core.proto", fileDescriptor_patch_core_8c48faa97cb34ef8) }

var fileDescriptor_patch_core_8c48faa97cb34ef8 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x18, 0x84, 0xd9, 0xb5, 0xf6, 0x10, 0x41, 0xea, 0x9e, 0x4a, 0x91, 0xba, 0xf4, 0xd4, 0x4b, 0x13,
	0xa9, 0xc5, 0x07, 0x50, 0x3c, 0x78, 0x93, 0x2d, 0x78, 0x2d, 0xe9, 0xf6, 0x37, 0x0d, 0xed, 0xe6,
	0x8f, 0xc9, 0xbf, 0x2d, 0xbe, 0x95, 0x6f, 0x24, 0xf8, 0x24, 0x92, 0xec, 0x6a, 0x8b, 0x20, 0xde,
	0x06, 0x32, 0x33, 0xf9, 0x26, 0x61, 0x3d, 0x2b, 0xa9, 0x5c, 0x2f, 0x4a, 0x74, 0xc0, 0xad, 0x43,
	0xc2, 0x6c, 0x20, 0x35, 0xaf, 0x80, 0x24, 0xad, 0xb5, 0x51, 0x9e, 0x7b, 0x70, 0x3b, 0x5d, 0x02,
	0x0f, 0x8e, 0xc1, 0x50, 0x21, 0xaa, 0x2d, 0x88, 0xe8, 0x5c, 0xd6, 0x2f, 0x62, 0xef, 0xa4, 0xb5,
	0xe0, 0x7c, 0x93, 0x1d, 0xdc, 0x2a, 0x4d, 0xeb, 0x7a, 0xc9, 0x4b, 0xac, 0x44, 0xb5, 0xd7, 0xb4,
	0xc1, 0xbd, 0x50, 0x38, 0x89, 0x87, 0x93, 0x9d, 0xdc, 0xea, 0x95, 0x24, 0x74, 0x5e, 0xfc, 0xc8,
	0x36, 0xf7, 0x70, 0x94, 0x33, 0xf2, 0x0d, 0x89, 0xa4, 0x38, 0x30, 0x08, 0xbb, 0x51, 0xcd, 0x95,
	0xa2, 0xc4, 0xaa, 0x42, 0x23, 0x3c, 0x49, 0x02, 0x11, 0x90, 0x16, 0x51, 0xb6, 0x35, 0xec, 0x30,
	0x63, 0xf4, 0x9e, 0xb0, 0xde, 0x53, 0xd8, 0x76, 0x8f, 0x0e, 0x0a, 0x78, 0xad, 0xc1, 0x53, 0x36,
	0x63, 0xa9, 0x5e, 0xf5, 0x93, 0x3c, 0x19, 0x9f, 0x4d, 0x2f, 0x79, 0x33, 0x86, 0x7f, 0x8f, 0xe1,
	0x73, 0x72, 0xda, 0xa8, 0x67, 0xb9, 0xad, 0xe1, 0xae, 0xfb, 0xf9, 0x71, 0x95, 0xe6, 0x49, 0x91,
	0xea, 0x55, 0x76, 0xcd, 0x3a, 0x46, 0x56, 0xd0, 0x4f, 0xff, 0xcf, 0x15, 0xd1, 0x99, 0xcd, 0xd8,
	0x69, 0xe4, 0xea, 0x9f, 0xe4, 0xc9, 0xf8, 0x7c, 0x3a, 0xe4, 0xbf, 0xde, 0x34, 0x32, 0x07, 0xb0,
	0x79, 0x50, 0x45, 0x63, 0x1e, 0x3d, 0xb2, 0x8b, 0x23, 0x62, 0x6f, 0xd1, 0xf8, 0x50, 0xd5, 0x09,
	0xab, 0x5a, 0xe8, 0x9c, 0xff, 0xfd, 0x3b, 0xb1, 0xb0, 0x88, 0xee, 0x65, 0x37, 0xc2, 0xdd, 0x7c,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xd8, 0xd7, 0xbf, 0xdf, 0x01, 0x00, 0x00,
}
