// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"
import google_protobuf2 "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StreamErrorResponsePayload struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	MethodName  string `protobuf:"bytes,3,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	Context     string `protobuf:"bytes,4,opt,name=context" json:"context,omitempty"`
}

func (m *StreamErrorResponsePayload) Reset()                    { *m = StreamErrorResponsePayload{} }
func (m *StreamErrorResponsePayload) String() string            { return proto.CompactTextString(m) }
func (*StreamErrorResponsePayload) ProtoMessage()               {}
func (*StreamErrorResponsePayload) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{0} }

func (m *StreamErrorResponsePayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamErrorResponsePayload) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *StreamErrorResponsePayload) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *StreamErrorResponsePayload) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type UnaryCallRequestPayload struct {
	Name        *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ServiceName *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	MethodName  *google_protobuf.StringValue `protobuf:"bytes,3,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	Payload     *google_protobuf2.Any        `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
}

func (m *UnaryCallRequestPayload) Reset()                    { *m = UnaryCallRequestPayload{} }
func (m *UnaryCallRequestPayload) String() string            { return proto.CompactTextString(m) }
func (*UnaryCallRequestPayload) ProtoMessage()               {}
func (*UnaryCallRequestPayload) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{1} }

func (m *UnaryCallRequestPayload) GetName() *google_protobuf.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UnaryCallRequestPayload) GetServiceName() *google_protobuf.StringValue {
	if m != nil {
		return m.ServiceName
	}
	return nil
}

func (m *UnaryCallRequestPayload) GetMethodName() *google_protobuf.StringValue {
	if m != nil {
		return m.MethodName
	}
	return nil
}

func (m *UnaryCallRequestPayload) GetPayload() *google_protobuf2.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UnaryCallResponsePayload struct {
	Name        string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ServiceName string                `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	MethodName  string                `protobuf:"bytes,3,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	Payload     *google_protobuf2.Any `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
}

func (m *UnaryCallResponsePayload) Reset()                    { *m = UnaryCallResponsePayload{} }
func (m *UnaryCallResponsePayload) String() string            { return proto.CompactTextString(m) }
func (*UnaryCallResponsePayload) ProtoMessage()               {}
func (*UnaryCallResponsePayload) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{2} }

func (m *UnaryCallResponsePayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnaryCallResponsePayload) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *UnaryCallResponsePayload) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *UnaryCallResponsePayload) GetPayload() *google_protobuf2.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamErrorResponsePayload)(nil), "ai.metathings.service.core.StreamErrorResponsePayload")
	proto.RegisterType((*UnaryCallRequestPayload)(nil), "ai.metathings.service.core.UnaryCallRequestPayload")
	proto.RegisterType((*UnaryCallResponsePayload)(nil), "ai.metathings.service.core.UnaryCallResponsePayload")
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor15) }

var fileDescriptor15 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x16, 0x8b, 0x1b, 0xbd, 0x04, 0xc1, 0x18, 0xc4, 0x3f, 0x3d, 0x79, 0xda, 0x4a,
	0x3d, 0x8b, 0x88, 0x78, 0x15, 0x49, 0xd1, 0xab, 0x4c, 0xd3, 0x31, 0x0d, 0x24, 0x3b, 0xeb, 0xec,
	0x46, 0xcd, 0x97, 0xf0, 0x43, 0xf8, 0x35, 0xbd, 0x88, 0xbb, 0x09, 0x44, 0x2b, 0x14, 0x2f, 0xde,
	0x76, 0xe7, 0xbd, 0xc7, 0xbc, 0x1f, 0x23, 0xb6, 0x35, 0x34, 0x25, 0xc1, 0x5c, 0x6a, 0x26, 0x4b,
	0x51, 0x02, 0x85, 0xac, 0xd0, 0x82, 0x5d, 0x14, 0x2a, 0x37, 0xd2, 0x20, 0x3f, 0x17, 0x19, 0xca,
	0x8c, 0x18, 0x93, 0x83, 0x9c, 0x28, 0x2f, 0x71, 0xec, 0x9c, 0xb3, 0xfa, 0x71, 0xfc, 0xc2, 0xa0,
	0x35, 0xb2, 0xf1, 0xd9, 0x64, 0xef, 0xa7, 0x0e, 0xaa, 0xf1, 0xd2, 0xe8, 0x2d, 0x10, 0xc9, 0xd4,
	0x32, 0x42, 0x75, 0xcd, 0x4c, 0x9c, 0xa2, 0xd1, 0xa4, 0x0c, 0xde, 0xfa, 0xdd, 0x51, 0x24, 0x06,
	0x0a, 0x2a, 0x8c, 0x83, 0xa3, 0xe0, 0x64, 0x33, 0x75, 0xef, 0xe8, 0x58, 0x6c, 0xb5, 0xdb, 0x1f,
	0x9c, 0xb6, 0xe6, 0xb4, 0xb0, 0x9d, 0xdd, 0x7c, 0x59, 0x0e, 0x45, 0x58, 0xa1, 0x5d, 0xd0, 0xdc,
	0x3b, 0xd6, 0x9d, 0x43, 0xf8, 0x91, 0x33, 0xc4, 0x62, 0x98, 0x91, 0xb2, 0xf8, 0x6a, 0xe3, 0x81,
	0x13, 0xbb, 0xef, 0xe8, 0x23, 0x10, 0xbb, 0x77, 0x0a, 0xb8, 0xb9, 0x82, 0xb2, 0x4c, 0xf1, 0xa9,
	0x46, 0x63, 0xbb, 0x36, 0xa7, 0xbd, 0x36, 0xe1, 0x64, 0x5f, 0x7a, 0x2c, 0xd9, 0x61, 0xc9, 0xa9,
	0xe5, 0x42, 0xe5, 0xf7, 0x50, 0xd6, 0xd8, 0x76, 0xbd, 0xf8, 0xa5, 0xeb, 0xaa, 0xe4, 0x37, 0x92,
	0xf3, 0x65, 0x92, 0x55, 0xf9, 0x3e, 0xa7, 0x14, 0xc3, 0xf6, 0x8c, 0x8e, 0x33, 0x9c, 0xec, 0x2c,
	0x45, 0x2f, 0x55, 0x93, 0x76, 0xa6, 0xd1, 0x7b, 0x20, 0xe2, 0x1e, 0xfd, 0xff, 0x1c, 0xe3, 0x8f,
	0x25, 0x67, 0x1b, 0x6e, 0x7c, 0xf6, 0x19, 0x00, 0x00, 0xff, 0xff, 0x52, 0xd4, 0xc4, 0x89, 0xa2,
	0x02, 0x00, 0x00,
}
