// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream_call.proto

package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamCallRequest struct {
	CoreId               *wrappers.StringValue     `protobuf:"bytes,1,opt,name=core_id,json=coreId" json:"core_id,omitempty"`
	Payload              *StreamCallRequestPayload `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *StreamCallRequest) Reset()         { *m = StreamCallRequest{} }
func (m *StreamCallRequest) String() string { return proto.CompactTextString(m) }
func (*StreamCallRequest) ProtoMessage()    {}
func (*StreamCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_call_38e1d4a6c284b846, []int{0}
}
func (m *StreamCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamCallRequest.Unmarshal(m, b)
}
func (m *StreamCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamCallRequest.Marshal(b, m, deterministic)
}
func (dst *StreamCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCallRequest.Merge(dst, src)
}
func (m *StreamCallRequest) XXX_Size() int {
	return xxx_messageInfo_StreamCallRequest.Size(m)
}
func (m *StreamCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCallRequest proto.InternalMessageInfo

func (m *StreamCallRequest) GetCoreId() *wrappers.StringValue {
	if m != nil {
		return m.CoreId
	}
	return nil
}

func (m *StreamCallRequest) GetPayload() *StreamCallRequestPayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type StreamCallResponse struct {
	Payload              *StreamCallResponsePayload `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StreamCallResponse) Reset()         { *m = StreamCallResponse{} }
func (m *StreamCallResponse) String() string { return proto.CompactTextString(m) }
func (*StreamCallResponse) ProtoMessage()    {}
func (*StreamCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_call_38e1d4a6c284b846, []int{1}
}
func (m *StreamCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamCallResponse.Unmarshal(m, b)
}
func (m *StreamCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamCallResponse.Marshal(b, m, deterministic)
}
func (dst *StreamCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamCallResponse.Merge(dst, src)
}
func (m *StreamCallResponse) XXX_Size() int {
	return xxx_messageInfo_StreamCallResponse.Size(m)
}
func (m *StreamCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamCallResponse proto.InternalMessageInfo

func (m *StreamCallResponse) GetPayload() *StreamCallResponsePayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamCallRequest)(nil), "ai.metathings.service.core.StreamCallRequest")
	proto.RegisterType((*StreamCallResponse)(nil), "ai.metathings.service.core.StreamCallResponse")
}

func init() { proto.RegisterFile("stream_call.proto", fileDescriptor_stream_call_38e1d4a6c284b846) }

var fileDescriptor_stream_call_38e1d4a6c284b846 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xa9, 0x87, 0x0d, 0x2a, 0x1e, 0xd6, 0xd3, 0x2c, 0x22, 0xb2, 0x93, 0x97, 0xbd, 0x80,
	0x3a, 0xff, 0x01, 0x4f, 0x5e, 0x54, 0x3a, 0xf0, 0x3a, 0x5e, 0xdb, 0x67, 0x16, 0x4c, 0xfb, 0x62,
	0x92, 0xae, 0xec, 0x5f, 0xf1, 0xaf, 0x95, 0x25, 0x9d, 0x48, 0x45, 0xf0, 0x96, 0xf0, 0xfd, 0xf5,
	0x79, 0xe9, 0xcc, 0x79, 0x4b, 0xd8, 0x6c, 0x2a, 0xd4, 0x1a, 0x8c, 0x65, 0xcf, 0x59, 0x8e, 0x0a,
	0x1a, 0xf2, 0xe8, 0xb7, 0xaa, 0x95, 0x0e, 0x1c, 0xd9, 0x9d, 0xaa, 0x08, 0x2a, 0xb6, 0x94, 0x5f,
	0x4a, 0x66, 0xa9, 0x49, 0x04, 0x67, 0xd9, 0xbd, 0x89, 0xde, 0xa2, 0x31, 0x64, 0x5d, 0xcc, 0xe6,
	0xe7, 0x63, 0x1d, 0xdb, 0xfd, 0x20, 0xdd, 0x4b, 0xe5, 0xb7, 0x5d, 0x09, 0x15, 0x37, 0xa2, 0xe9,
	0x95, 0x7f, 0xe7, 0x5e, 0x48, 0x5e, 0x06, 0x71, 0xb9, 0x43, 0xad, 0x6a, 0xf4, 0x6c, 0x9d, 0xf8,
	0x7e, 0x0e, 0xb9, 0x33, 0x83, 0x7b, 0xcd, 0x58, 0xc7, 0xef, 0xe2, 0x33, 0x49, 0x67, 0xeb, 0xc0,
	0xfc, 0x80, 0x5a, 0x17, 0xf4, 0xd1, 0x91, 0xf3, 0xd9, 0x2a, 0x9d, 0x1e, 0xf8, 0x36, 0xaa, 0x9e,
	0x27, 0x57, 0xc9, 0xf5, 0xe9, 0xcd, 0x05, 0x44, 0x12, 0x38, 0x92, 0xc0, 0xda, 0x5b, 0xd5, 0xca,
	0x57, 0xd4, 0x1d, 0x15, 0x93, 0x83, 0xf9, 0xb1, 0xce, 0x9e, 0xd2, 0xe9, 0xd0, 0x3e, 0x3f, 0x09,
	0xb1, 0x3b, 0xf8, 0xfb, 0x78, 0xf8, 0x35, 0xfb, 0x12, 0xb3, 0xc5, 0xb1, 0x64, 0x41, 0x69, 0xf6,
	0xd3, 0xe4, 0x0c, 0xb7, 0x8e, 0xb2, 0xe7, 0xf1, 0xca, 0xea, 0xbf, 0x2b, 0xb1, 0x60, 0x3c, 0x53,
	0x4e, 0xc2, 0x51, 0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xc0, 0x93, 0x8d, 0xbd, 0x01,
	0x00, 0x00,
}
