FROM bigdatagz/metathings-protobuf

RUN go get -u -v github.com/golang/protobuf/proto && \
    go get -u -v github.com/golang/protobuf/protoc-gen-go && \
    go get -u -v github.com/mwitkow/go-proto-validators/protoc-gen-govalidators
