FROM nayotta/metathingsd

COPY ./etc/device_cloud.yaml /etc/metathings/device_cloud.yaml
COPY ./script/device_cloud_start.sh /usr/local/sbin/device_cloud_start.sh
CMD /usr/local/sbin/device_cloud_start.sh
