FROM bigdatagz/metathings-protobuf-arm

RUN export GOOS=linux && \
    export GOARCH=amd64 && \
    export CC=gcc && \
    unset GOARM && \
    go get -u github.com/golang/protobuf/protoc-gen-go && \
    go get -u github.com/mwitkow/go-proto-validators/protoc-gen-govalidators && \
