FROM e3rp4y/rpi-cross-compiler-platform

RUN apt update && \
    apt install -y build-essential git autoconf automake libtool unzip && \
    git clone https://github.com/google/protobuf -b v3.5.1 --depth 1 && \
    cd protobuf && \
    ./autogen.sh && \
    ./configure --prefix=/usr && \
    make && \
    make check && \
    make install && \
    cd .. && \
    rm -rf protobuf
