FROM nayotta/metathings-development

COPY ./etc/policyd.yaml /etc/metathings/policyd.yaml
COPY ./script/policyd.dev_start.sh /usr/local/sbin/policyd.dev_start.sh
CMD /usr/local/sbin/policyd.dev_start.sh
