package constant_helper

import "fmt"

const (
	CONSTANT_METATHINGSD_DEFAULT_HOST = "mt-api.nayotta.com"
	CONSTANT_METATHINGSD_DEFAULT_PORT = 21733

	CONSTANT_CORE_AGENTD_DEFAULT_HOST = "agentd.metathings.local:5002"
	CONSTANT_CORE_AGENTD_DEFAULT_PORT = 5002
)

var (
	CONSTANT_METATHINGSD_ADDRESS = fmt.Sprintf("%v:%v", CONSTANT_METATHINGSD_DEFAULT_HOST, CONSTANT_METATHINGSD_DEFAULT_PORT)
	CONSTANT_CORE_AGENTD_ADDRESS = fmt.Sprintf("%v:%v", CONSTANT_CORE_AGENTD_DEFAULT_HOST, CONSTANT_CORE_AGENTD_DEFAULT_PORT)
)
