package constant_helper

import "fmt"

const (
	CONSTANT_METATHINGSD_DEFAULT_HOST = "api.metathings.nayotta.com"
	CONSTANT_METATHINGSD_DEFAULT_PORT = 21733

	CONSTANT_CORE_AGENT_DEFAULT_HOST = "localhost"
	CONSTANT_CORE_AGENT_DEFAULT_PORT = 5002
)

var (
	CONSTANT_METATHINGSD_ADDRESS = fmt.Sprintf("%v:%v", CONSTANT_METATHINGSD_DEFAULT_HOST, CONSTANT_METATHINGSD_DEFAULT_PORT)
	CONSTANT_CORE_AGENT_ADDRESS  = fmt.Sprintf("%v:%v", CONSTANT_CORE_AGENT_DEFAULT_HOST, CONSTANT_CORE_AGENT_DEFAULT_PORT)
)
