// Code generated by protoc-gen-go. DO NOT EDIT.
// source: esp8266_mqtt.proto

package device_cloud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MqttDeviceRequest struct {
	SessionId int32 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*MqttDeviceRequest_GpioDigital
	//	*MqttDeviceRequest_GpioAnalog
	//	*MqttDeviceRequest_I2C
	//	*MqttDeviceRequest_Heartbeat
	//	*MqttDeviceRequest_HeartbeatSelectRes
	//	*MqttDeviceRequest_HeartbeatRes
	//	*MqttDeviceRequest_RunTime
	//	*MqttDeviceRequest_Config
	Payload              isMqttDeviceRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MqttDeviceRequest) Reset()         { *m = MqttDeviceRequest{} }
func (m *MqttDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*MqttDeviceRequest) ProtoMessage()    {}
func (*MqttDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{0}
}

func (m *MqttDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MqttDeviceRequest.Unmarshal(m, b)
}
func (m *MqttDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MqttDeviceRequest.Marshal(b, m, deterministic)
}
func (m *MqttDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MqttDeviceRequest.Merge(m, src)
}
func (m *MqttDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_MqttDeviceRequest.Size(m)
}
func (m *MqttDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MqttDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MqttDeviceRequest proto.InternalMessageInfo

func (m *MqttDeviceRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type isMqttDeviceRequest_Payload interface {
	isMqttDeviceRequest_Payload()
}

type MqttDeviceRequest_GpioDigital struct {
	GpioDigital *GpioDigitalPayload `protobuf:"bytes,2,opt,name=gpio_digital,json=gpioDigital,proto3,oneof"`
}

type MqttDeviceRequest_GpioAnalog struct {
	GpioAnalog *GpioAnalogPayload `protobuf:"bytes,3,opt,name=gpio_analog,json=gpioAnalog,proto3,oneof"`
}

type MqttDeviceRequest_I2C struct {
	I2C *I2CPayload `protobuf:"bytes,4,opt,name=i2c,proto3,oneof"`
}

type MqttDeviceRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,100,opt,name=heartbeat,proto3,oneof"`
}

type MqttDeviceRequest_HeartbeatSelectRes struct {
	HeartbeatSelectRes *HeartbeatSelectRes `protobuf:"bytes,101,opt,name=heartbeat_select_res,json=heartbeatSelectRes,proto3,oneof"`
}

type MqttDeviceRequest_HeartbeatRes struct {
	HeartbeatRes *HeartbeatRes `protobuf:"bytes,102,opt,name=heartbeat_res,json=heartbeatRes,proto3,oneof"`
}

type MqttDeviceRequest_RunTime struct {
	RunTime *RunTimePayload `protobuf:"bytes,103,opt,name=run_time,json=runTime,proto3,oneof"`
}

type MqttDeviceRequest_Config struct {
	Config *ConfigPayload `protobuf:"bytes,104,opt,name=config,proto3,oneof"`
}

func (*MqttDeviceRequest_GpioDigital) isMqttDeviceRequest_Payload() {}

func (*MqttDeviceRequest_GpioAnalog) isMqttDeviceRequest_Payload() {}

func (*MqttDeviceRequest_I2C) isMqttDeviceRequest_Payload() {}

func (*MqttDeviceRequest_Heartbeat) isMqttDeviceRequest_Payload() {}

func (*MqttDeviceRequest_HeartbeatSelectRes) isMqttDeviceRequest_Payload() {}

func (*MqttDeviceRequest_HeartbeatRes) isMqttDeviceRequest_Payload() {}

func (*MqttDeviceRequest_RunTime) isMqttDeviceRequest_Payload() {}

func (*MqttDeviceRequest_Config) isMqttDeviceRequest_Payload() {}

func (m *MqttDeviceRequest) GetPayload() isMqttDeviceRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MqttDeviceRequest) GetGpioDigital() *GpioDigitalPayload {
	if x, ok := m.GetPayload().(*MqttDeviceRequest_GpioDigital); ok {
		return x.GpioDigital
	}
	return nil
}

func (m *MqttDeviceRequest) GetGpioAnalog() *GpioAnalogPayload {
	if x, ok := m.GetPayload().(*MqttDeviceRequest_GpioAnalog); ok {
		return x.GpioAnalog
	}
	return nil
}

func (m *MqttDeviceRequest) GetI2C() *I2CPayload {
	if x, ok := m.GetPayload().(*MqttDeviceRequest_I2C); ok {
		return x.I2C
	}
	return nil
}

func (m *MqttDeviceRequest) GetHeartbeat() *Heartbeat {
	if x, ok := m.GetPayload().(*MqttDeviceRequest_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *MqttDeviceRequest) GetHeartbeatSelectRes() *HeartbeatSelectRes {
	if x, ok := m.GetPayload().(*MqttDeviceRequest_HeartbeatSelectRes); ok {
		return x.HeartbeatSelectRes
	}
	return nil
}

func (m *MqttDeviceRequest) GetHeartbeatRes() *HeartbeatRes {
	if x, ok := m.GetPayload().(*MqttDeviceRequest_HeartbeatRes); ok {
		return x.HeartbeatRes
	}
	return nil
}

func (m *MqttDeviceRequest) GetRunTime() *RunTimePayload {
	if x, ok := m.GetPayload().(*MqttDeviceRequest_RunTime); ok {
		return x.RunTime
	}
	return nil
}

func (m *MqttDeviceRequest) GetConfig() *ConfigPayload {
	if x, ok := m.GetPayload().(*MqttDeviceRequest_Config); ok {
		return x.Config
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MqttDeviceRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MqttDeviceRequest_OneofMarshaler, _MqttDeviceRequest_OneofUnmarshaler, _MqttDeviceRequest_OneofSizer, []interface{}{
		(*MqttDeviceRequest_GpioDigital)(nil),
		(*MqttDeviceRequest_GpioAnalog)(nil),
		(*MqttDeviceRequest_I2C)(nil),
		(*MqttDeviceRequest_Heartbeat)(nil),
		(*MqttDeviceRequest_HeartbeatSelectRes)(nil),
		(*MqttDeviceRequest_HeartbeatRes)(nil),
		(*MqttDeviceRequest_RunTime)(nil),
		(*MqttDeviceRequest_Config)(nil),
	}
}

func _MqttDeviceRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MqttDeviceRequest)
	// payload
	switch x := m.Payload.(type) {
	case *MqttDeviceRequest_GpioDigital:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GpioDigital); err != nil {
			return err
		}
	case *MqttDeviceRequest_GpioAnalog:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GpioAnalog); err != nil {
			return err
		}
	case *MqttDeviceRequest_I2C:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.I2C); err != nil {
			return err
		}
	case *MqttDeviceRequest_Heartbeat:
		b.EncodeVarint(100<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Heartbeat); err != nil {
			return err
		}
	case *MqttDeviceRequest_HeartbeatSelectRes:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HeartbeatSelectRes); err != nil {
			return err
		}
	case *MqttDeviceRequest_HeartbeatRes:
		b.EncodeVarint(102<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HeartbeatRes); err != nil {
			return err
		}
	case *MqttDeviceRequest_RunTime:
		b.EncodeVarint(103<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RunTime); err != nil {
			return err
		}
	case *MqttDeviceRequest_Config:
		b.EncodeVarint(104<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Config); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MqttDeviceRequest.Payload has unexpected type %T", x)
	}
	return nil
}

func _MqttDeviceRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MqttDeviceRequest)
	switch tag {
	case 2: // payload.gpio_digital
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GpioDigitalPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceRequest_GpioDigital{msg}
		return true, err
	case 3: // payload.gpio_analog
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GpioAnalogPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceRequest_GpioAnalog{msg}
		return true, err
	case 4: // payload.i2c
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(I2CPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceRequest_I2C{msg}
		return true, err
	case 100: // payload.heartbeat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Heartbeat)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceRequest_Heartbeat{msg}
		return true, err
	case 101: // payload.heartbeat_select_res
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HeartbeatSelectRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceRequest_HeartbeatSelectRes{msg}
		return true, err
	case 102: // payload.heartbeat_res
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HeartbeatRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceRequest_HeartbeatRes{msg}
		return true, err
	case 103: // payload.run_time
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RunTimePayload)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceRequest_RunTime{msg}
		return true, err
	case 104: // payload.config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConfigPayload)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceRequest_Config{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MqttDeviceRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MqttDeviceRequest)
	// payload
	switch x := m.Payload.(type) {
	case *MqttDeviceRequest_GpioDigital:
		s := proto.Size(x.GpioDigital)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceRequest_GpioAnalog:
		s := proto.Size(x.GpioAnalog)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceRequest_I2C:
		s := proto.Size(x.I2C)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceRequest_Heartbeat:
		s := proto.Size(x.Heartbeat)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceRequest_HeartbeatSelectRes:
		s := proto.Size(x.HeartbeatSelectRes)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceRequest_HeartbeatRes:
		s := proto.Size(x.HeartbeatRes)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceRequest_RunTime:
		s := proto.Size(x.RunTime)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceRequest_Config:
		s := proto.Size(x.Config)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MqttDeviceResponse struct {
	// Types that are valid to be assigned to Payload:
	//	*MqttDeviceResponse_GpioDigital
	//	*MqttDeviceResponse_GpioAnalog
	//	*MqttDeviceResponse_I2C
	//	*MqttDeviceResponse_BadArgs
	//	*MqttDeviceResponse_HeartbeatSelectReq
	//	*MqttDeviceResponse_Heartbeat
	//	*MqttDeviceResponse_HeartbeatReq
	//	*MqttDeviceResponse_RunTime
	//	*MqttDeviceResponse_Config
	Payload              isMqttDeviceResponse_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MqttDeviceResponse) Reset()         { *m = MqttDeviceResponse{} }
func (m *MqttDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*MqttDeviceResponse) ProtoMessage()    {}
func (*MqttDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{1}
}

func (m *MqttDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MqttDeviceResponse.Unmarshal(m, b)
}
func (m *MqttDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MqttDeviceResponse.Marshal(b, m, deterministic)
}
func (m *MqttDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MqttDeviceResponse.Merge(m, src)
}
func (m *MqttDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_MqttDeviceResponse.Size(m)
}
func (m *MqttDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MqttDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MqttDeviceResponse proto.InternalMessageInfo

type isMqttDeviceResponse_Payload interface {
	isMqttDeviceResponse_Payload()
}

type MqttDeviceResponse_GpioDigital struct {
	GpioDigital *GpioDigitalPayloadRes `protobuf:"bytes,2,opt,name=gpio_digital,json=gpioDigital,proto3,oneof"`
}

type MqttDeviceResponse_GpioAnalog struct {
	GpioAnalog *GpioAnalogPayloadRes `protobuf:"bytes,3,opt,name=gpio_analog,json=gpioAnalog,proto3,oneof"`
}

type MqttDeviceResponse_I2C struct {
	I2C *I2CPayloadRes `protobuf:"bytes,4,opt,name=i2c,proto3,oneof"`
}

type MqttDeviceResponse_BadArgs struct {
	BadArgs *ErrBadArgsRes `protobuf:"bytes,99,opt,name=bad_args,json=badArgs,proto3,oneof"`
}

type MqttDeviceResponse_HeartbeatSelectReq struct {
	HeartbeatSelectReq *HeartbeatSelectReq `protobuf:"bytes,100,opt,name=heartbeat_select_req,json=heartbeatSelectReq,proto3,oneof"`
}

type MqttDeviceResponse_Heartbeat struct {
	Heartbeat *HeartbeatRes `protobuf:"bytes,101,opt,name=heartbeat,proto3,oneof"`
}

type MqttDeviceResponse_HeartbeatReq struct {
	HeartbeatReq *HeartbeatReq `protobuf:"bytes,102,opt,name=heartbeat_req,json=heartbeatReq,proto3,oneof"`
}

type MqttDeviceResponse_RunTime struct {
	RunTime *RunTimeRes `protobuf:"bytes,103,opt,name=run_time,json=runTime,proto3,oneof"`
}

type MqttDeviceResponse_Config struct {
	Config *ConfigRes `protobuf:"bytes,104,opt,name=config,proto3,oneof"`
}

func (*MqttDeviceResponse_GpioDigital) isMqttDeviceResponse_Payload() {}

func (*MqttDeviceResponse_GpioAnalog) isMqttDeviceResponse_Payload() {}

func (*MqttDeviceResponse_I2C) isMqttDeviceResponse_Payload() {}

func (*MqttDeviceResponse_BadArgs) isMqttDeviceResponse_Payload() {}

func (*MqttDeviceResponse_HeartbeatSelectReq) isMqttDeviceResponse_Payload() {}

func (*MqttDeviceResponse_Heartbeat) isMqttDeviceResponse_Payload() {}

func (*MqttDeviceResponse_HeartbeatReq) isMqttDeviceResponse_Payload() {}

func (*MqttDeviceResponse_RunTime) isMqttDeviceResponse_Payload() {}

func (*MqttDeviceResponse_Config) isMqttDeviceResponse_Payload() {}

func (m *MqttDeviceResponse) GetPayload() isMqttDeviceResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MqttDeviceResponse) GetGpioDigital() *GpioDigitalPayloadRes {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_GpioDigital); ok {
		return x.GpioDigital
	}
	return nil
}

func (m *MqttDeviceResponse) GetGpioAnalog() *GpioAnalogPayloadRes {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_GpioAnalog); ok {
		return x.GpioAnalog
	}
	return nil
}

func (m *MqttDeviceResponse) GetI2C() *I2CPayloadRes {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_I2C); ok {
		return x.I2C
	}
	return nil
}

func (m *MqttDeviceResponse) GetBadArgs() *ErrBadArgsRes {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_BadArgs); ok {
		return x.BadArgs
	}
	return nil
}

func (m *MqttDeviceResponse) GetHeartbeatSelectReq() *HeartbeatSelectReq {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_HeartbeatSelectReq); ok {
		return x.HeartbeatSelectReq
	}
	return nil
}

func (m *MqttDeviceResponse) GetHeartbeat() *HeartbeatRes {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *MqttDeviceResponse) GetHeartbeatReq() *HeartbeatReq {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_HeartbeatReq); ok {
		return x.HeartbeatReq
	}
	return nil
}

func (m *MqttDeviceResponse) GetRunTime() *RunTimeRes {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_RunTime); ok {
		return x.RunTime
	}
	return nil
}

func (m *MqttDeviceResponse) GetConfig() *ConfigRes {
	if x, ok := m.GetPayload().(*MqttDeviceResponse_Config); ok {
		return x.Config
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MqttDeviceResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MqttDeviceResponse_OneofMarshaler, _MqttDeviceResponse_OneofUnmarshaler, _MqttDeviceResponse_OneofSizer, []interface{}{
		(*MqttDeviceResponse_GpioDigital)(nil),
		(*MqttDeviceResponse_GpioAnalog)(nil),
		(*MqttDeviceResponse_I2C)(nil),
		(*MqttDeviceResponse_BadArgs)(nil),
		(*MqttDeviceResponse_HeartbeatSelectReq)(nil),
		(*MqttDeviceResponse_Heartbeat)(nil),
		(*MqttDeviceResponse_HeartbeatReq)(nil),
		(*MqttDeviceResponse_RunTime)(nil),
		(*MqttDeviceResponse_Config)(nil),
	}
}

func _MqttDeviceResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MqttDeviceResponse)
	// payload
	switch x := m.Payload.(type) {
	case *MqttDeviceResponse_GpioDigital:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GpioDigital); err != nil {
			return err
		}
	case *MqttDeviceResponse_GpioAnalog:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GpioAnalog); err != nil {
			return err
		}
	case *MqttDeviceResponse_I2C:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.I2C); err != nil {
			return err
		}
	case *MqttDeviceResponse_BadArgs:
		b.EncodeVarint(99<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BadArgs); err != nil {
			return err
		}
	case *MqttDeviceResponse_HeartbeatSelectReq:
		b.EncodeVarint(100<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HeartbeatSelectReq); err != nil {
			return err
		}
	case *MqttDeviceResponse_Heartbeat:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Heartbeat); err != nil {
			return err
		}
	case *MqttDeviceResponse_HeartbeatReq:
		b.EncodeVarint(102<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HeartbeatReq); err != nil {
			return err
		}
	case *MqttDeviceResponse_RunTime:
		b.EncodeVarint(103<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RunTime); err != nil {
			return err
		}
	case *MqttDeviceResponse_Config:
		b.EncodeVarint(104<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Config); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MqttDeviceResponse.Payload has unexpected type %T", x)
	}
	return nil
}

func _MqttDeviceResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MqttDeviceResponse)
	switch tag {
	case 2: // payload.gpio_digital
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GpioDigitalPayloadRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_GpioDigital{msg}
		return true, err
	case 3: // payload.gpio_analog
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GpioAnalogPayloadRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_GpioAnalog{msg}
		return true, err
	case 4: // payload.i2c
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(I2CPayloadRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_I2C{msg}
		return true, err
	case 99: // payload.bad_args
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrBadArgsRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_BadArgs{msg}
		return true, err
	case 100: // payload.heartbeat_select_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HeartbeatSelectReq)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_HeartbeatSelectReq{msg}
		return true, err
	case 101: // payload.heartbeat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HeartbeatRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_Heartbeat{msg}
		return true, err
	case 102: // payload.heartbeat_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HeartbeatReq)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_HeartbeatReq{msg}
		return true, err
	case 103: // payload.run_time
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RunTimeRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_RunTime{msg}
		return true, err
	case 104: // payload.config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConfigRes)
		err := b.DecodeMessage(msg)
		m.Payload = &MqttDeviceResponse_Config{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MqttDeviceResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MqttDeviceResponse)
	// payload
	switch x := m.Payload.(type) {
	case *MqttDeviceResponse_GpioDigital:
		s := proto.Size(x.GpioDigital)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceResponse_GpioAnalog:
		s := proto.Size(x.GpioAnalog)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceResponse_I2C:
		s := proto.Size(x.I2C)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceResponse_BadArgs:
		s := proto.Size(x.BadArgs)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceResponse_HeartbeatSelectReq:
		s := proto.Size(x.HeartbeatSelectReq)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceResponse_Heartbeat:
		s := proto.Size(x.Heartbeat)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceResponse_HeartbeatReq:
		s := proto.Size(x.HeartbeatReq)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceResponse_RunTime:
		s := proto.Size(x.RunTime)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MqttDeviceResponse_Config:
		s := proto.Size(x.Config)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ConfigRes struct {
	Config               int32    `protobuf:"varint,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRes) Reset()         { *m = ConfigRes{} }
func (m *ConfigRes) String() string { return proto.CompactTextString(m) }
func (*ConfigRes) ProtoMessage()    {}
func (*ConfigRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{2}
}

func (m *ConfigRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRes.Unmarshal(m, b)
}
func (m *ConfigRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRes.Marshal(b, m, deterministic)
}
func (m *ConfigRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRes.Merge(m, src)
}
func (m *ConfigRes) XXX_Size() int {
	return xxx_messageInfo_ConfigRes.Size(m)
}
func (m *ConfigRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRes.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRes proto.InternalMessageInfo

func (m *ConfigRes) GetConfig() int32 {
	if m != nil {
		return m.Config
	}
	return 0
}

type ConfigPayload struct {
	Config               int32    `protobuf:"varint,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigPayload) Reset()         { *m = ConfigPayload{} }
func (m *ConfigPayload) String() string { return proto.CompactTextString(m) }
func (*ConfigPayload) ProtoMessage()    {}
func (*ConfigPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{3}
}

func (m *ConfigPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigPayload.Unmarshal(m, b)
}
func (m *ConfigPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigPayload.Marshal(b, m, deterministic)
}
func (m *ConfigPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigPayload.Merge(m, src)
}
func (m *ConfigPayload) XXX_Size() int {
	return xxx_messageInfo_ConfigPayload.Size(m)
}
func (m *ConfigPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigPayload proto.InternalMessageInfo

func (m *ConfigPayload) GetConfig() int32 {
	if m != nil {
		return m.Config
	}
	return 0
}

type RunTimeRes struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	AppStartTime         int64    `protobuf:"varint,2,opt,name=app_start_time,json=appStartTime,proto3" json:"app_start_time,omitempty"`
	RestartTimes         int32    `protobuf:"varint,3,opt,name=restart_times,json=restartTimes,proto3" json:"restart_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunTimeRes) Reset()         { *m = RunTimeRes{} }
func (m *RunTimeRes) String() string { return proto.CompactTextString(m) }
func (*RunTimeRes) ProtoMessage()    {}
func (*RunTimeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{4}
}

func (m *RunTimeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTimeRes.Unmarshal(m, b)
}
func (m *RunTimeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTimeRes.Marshal(b, m, deterministic)
}
func (m *RunTimeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTimeRes.Merge(m, src)
}
func (m *RunTimeRes) XXX_Size() int {
	return xxx_messageInfo_RunTimeRes.Size(m)
}
func (m *RunTimeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTimeRes.DiscardUnknown(m)
}

var xxx_messageInfo_RunTimeRes proto.InternalMessageInfo

func (m *RunTimeRes) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RunTimeRes) GetAppStartTime() int64 {
	if m != nil {
		return m.AppStartTime
	}
	return 0
}

func (m *RunTimeRes) GetRestartTimes() int32 {
	if m != nil {
		return m.RestartTimes
	}
	return 0
}

type RunTimePayload struct {
	Time                 int32    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunTimePayload) Reset()         { *m = RunTimePayload{} }
func (m *RunTimePayload) String() string { return proto.CompactTextString(m) }
func (*RunTimePayload) ProtoMessage()    {}
func (*RunTimePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{5}
}

func (m *RunTimePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTimePayload.Unmarshal(m, b)
}
func (m *RunTimePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTimePayload.Marshal(b, m, deterministic)
}
func (m *RunTimePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTimePayload.Merge(m, src)
}
func (m *RunTimePayload) XXX_Size() int {
	return xxx_messageInfo_RunTimePayload.Size(m)
}
func (m *RunTimePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTimePayload.DiscardUnknown(m)
}

var xxx_messageInfo_RunTimePayload proto.InternalMessageInfo

func (m *RunTimePayload) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type ErrBadArgsRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrBadArgsRes) Reset()         { *m = ErrBadArgsRes{} }
func (m *ErrBadArgsRes) String() string { return proto.CompactTextString(m) }
func (*ErrBadArgsRes) ProtoMessage()    {}
func (*ErrBadArgsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{6}
}

func (m *ErrBadArgsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrBadArgsRes.Unmarshal(m, b)
}
func (m *ErrBadArgsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrBadArgsRes.Marshal(b, m, deterministic)
}
func (m *ErrBadArgsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrBadArgsRes.Merge(m, src)
}
func (m *ErrBadArgsRes) XXX_Size() int {
	return xxx_messageInfo_ErrBadArgsRes.Size(m)
}
func (m *ErrBadArgsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrBadArgsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ErrBadArgsRes proto.InternalMessageInfo

func (m *ErrBadArgsRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Heartbeat struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{7}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type HeartbeatRes struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRes) Reset()         { *m = HeartbeatRes{} }
func (m *HeartbeatRes) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRes) ProtoMessage()    {}
func (*HeartbeatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{8}
}

func (m *HeartbeatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRes.Unmarshal(m, b)
}
func (m *HeartbeatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRes.Marshal(b, m, deterministic)
}
func (m *HeartbeatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRes.Merge(m, src)
}
func (m *HeartbeatRes) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRes.Size(m)
}
func (m *HeartbeatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRes.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRes proto.InternalMessageInfo

func (m *HeartbeatRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type HeartbeatReq struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatReq) Reset()         { *m = HeartbeatReq{} }
func (m *HeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartbeatReq) ProtoMessage()    {}
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{9}
}

func (m *HeartbeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatReq.Unmarshal(m, b)
}
func (m *HeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatReq.Marshal(b, m, deterministic)
}
func (m *HeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatReq.Merge(m, src)
}
func (m *HeartbeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartbeatReq.Size(m)
}
func (m *HeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatReq proto.InternalMessageInfo

func (m *HeartbeatReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type HeartbeatSelectRes struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatSelectRes) Reset()         { *m = HeartbeatSelectRes{} }
func (m *HeartbeatSelectRes) String() string { return proto.CompactTextString(m) }
func (*HeartbeatSelectRes) ProtoMessage()    {}
func (*HeartbeatSelectRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{10}
}

func (m *HeartbeatSelectRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatSelectRes.Unmarshal(m, b)
}
func (m *HeartbeatSelectRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatSelectRes.Marshal(b, m, deterministic)
}
func (m *HeartbeatSelectRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatSelectRes.Merge(m, src)
}
func (m *HeartbeatSelectRes) XXX_Size() int {
	return xxx_messageInfo_HeartbeatSelectRes.Size(m)
}
func (m *HeartbeatSelectRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatSelectRes.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatSelectRes proto.InternalMessageInfo

func (m *HeartbeatSelectRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type HeartbeatSelectReq struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatSelectReq) Reset()         { *m = HeartbeatSelectReq{} }
func (m *HeartbeatSelectReq) String() string { return proto.CompactTextString(m) }
func (*HeartbeatSelectReq) ProtoMessage()    {}
func (*HeartbeatSelectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{11}
}

func (m *HeartbeatSelectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatSelectReq.Unmarshal(m, b)
}
func (m *HeartbeatSelectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatSelectReq.Marshal(b, m, deterministic)
}
func (m *HeartbeatSelectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatSelectReq.Merge(m, src)
}
func (m *HeartbeatSelectReq) XXX_Size() int {
	return xxx_messageInfo_HeartbeatSelectReq.Size(m)
}
func (m *HeartbeatSelectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatSelectReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatSelectReq proto.InternalMessageInfo

func (m *HeartbeatSelectReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GpioDigitalPayload struct {
	Pin                  int32    `protobuf:"varint,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GpioDigitalPayload) Reset()         { *m = GpioDigitalPayload{} }
func (m *GpioDigitalPayload) String() string { return proto.CompactTextString(m) }
func (*GpioDigitalPayload) ProtoMessage()    {}
func (*GpioDigitalPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{12}
}

func (m *GpioDigitalPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GpioDigitalPayload.Unmarshal(m, b)
}
func (m *GpioDigitalPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GpioDigitalPayload.Marshal(b, m, deterministic)
}
func (m *GpioDigitalPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GpioDigitalPayload.Merge(m, src)
}
func (m *GpioDigitalPayload) XXX_Size() int {
	return xxx_messageInfo_GpioDigitalPayload.Size(m)
}
func (m *GpioDigitalPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_GpioDigitalPayload.DiscardUnknown(m)
}

var xxx_messageInfo_GpioDigitalPayload proto.InternalMessageInfo

func (m *GpioDigitalPayload) GetPin() int32 {
	if m != nil {
		return m.Pin
	}
	return 0
}

func (m *GpioDigitalPayload) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GpioDigitalPayloadRes struct {
	Pin                  int32    `protobuf:"varint,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GpioDigitalPayloadRes) Reset()         { *m = GpioDigitalPayloadRes{} }
func (m *GpioDigitalPayloadRes) String() string { return proto.CompactTextString(m) }
func (*GpioDigitalPayloadRes) ProtoMessage()    {}
func (*GpioDigitalPayloadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{13}
}

func (m *GpioDigitalPayloadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GpioDigitalPayloadRes.Unmarshal(m, b)
}
func (m *GpioDigitalPayloadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GpioDigitalPayloadRes.Marshal(b, m, deterministic)
}
func (m *GpioDigitalPayloadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GpioDigitalPayloadRes.Merge(m, src)
}
func (m *GpioDigitalPayloadRes) XXX_Size() int {
	return xxx_messageInfo_GpioDigitalPayloadRes.Size(m)
}
func (m *GpioDigitalPayloadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GpioDigitalPayloadRes.DiscardUnknown(m)
}

var xxx_messageInfo_GpioDigitalPayloadRes proto.InternalMessageInfo

func (m *GpioDigitalPayloadRes) GetPin() int32 {
	if m != nil {
		return m.Pin
	}
	return 0
}

func (m *GpioDigitalPayloadRes) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GpioAnalogPayload struct {
	Pin                  int32    `protobuf:"varint,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GpioAnalogPayload) Reset()         { *m = GpioAnalogPayload{} }
func (m *GpioAnalogPayload) String() string { return proto.CompactTextString(m) }
func (*GpioAnalogPayload) ProtoMessage()    {}
func (*GpioAnalogPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{14}
}

func (m *GpioAnalogPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GpioAnalogPayload.Unmarshal(m, b)
}
func (m *GpioAnalogPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GpioAnalogPayload.Marshal(b, m, deterministic)
}
func (m *GpioAnalogPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GpioAnalogPayload.Merge(m, src)
}
func (m *GpioAnalogPayload) XXX_Size() int {
	return xxx_messageInfo_GpioAnalogPayload.Size(m)
}
func (m *GpioAnalogPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_GpioAnalogPayload.DiscardUnknown(m)
}

var xxx_messageInfo_GpioAnalogPayload proto.InternalMessageInfo

func (m *GpioAnalogPayload) GetPin() int32 {
	if m != nil {
		return m.Pin
	}
	return 0
}

func (m *GpioAnalogPayload) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GpioAnalogPayloadRes struct {
	Pin                  int32    `protobuf:"varint,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GpioAnalogPayloadRes) Reset()         { *m = GpioAnalogPayloadRes{} }
func (m *GpioAnalogPayloadRes) String() string { return proto.CompactTextString(m) }
func (*GpioAnalogPayloadRes) ProtoMessage()    {}
func (*GpioAnalogPayloadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{15}
}

func (m *GpioAnalogPayloadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GpioAnalogPayloadRes.Unmarshal(m, b)
}
func (m *GpioAnalogPayloadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GpioAnalogPayloadRes.Marshal(b, m, deterministic)
}
func (m *GpioAnalogPayloadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GpioAnalogPayloadRes.Merge(m, src)
}
func (m *GpioAnalogPayloadRes) XXX_Size() int {
	return xxx_messageInfo_GpioAnalogPayloadRes.Size(m)
}
func (m *GpioAnalogPayloadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GpioAnalogPayloadRes.DiscardUnknown(m)
}

var xxx_messageInfo_GpioAnalogPayloadRes proto.InternalMessageInfo

func (m *GpioAnalogPayloadRes) GetPin() int32 {
	if m != nil {
		return m.Pin
	}
	return 0
}

func (m *GpioAnalogPayloadRes) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type I2CPayload struct {
	Bus                  int32    `protobuf:"varint,1,opt,name=bus,proto3" json:"bus,omitempty"`
	Addr                 int32    `protobuf:"varint,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Index                int32    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Angle                int32    `protobuf:"varint,4,opt,name=angle,proto3" json:"angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *I2CPayload) Reset()         { *m = I2CPayload{} }
func (m *I2CPayload) String() string { return proto.CompactTextString(m) }
func (*I2CPayload) ProtoMessage()    {}
func (*I2CPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{16}
}

func (m *I2CPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_I2CPayload.Unmarshal(m, b)
}
func (m *I2CPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_I2CPayload.Marshal(b, m, deterministic)
}
func (m *I2CPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_I2CPayload.Merge(m, src)
}
func (m *I2CPayload) XXX_Size() int {
	return xxx_messageInfo_I2CPayload.Size(m)
}
func (m *I2CPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_I2CPayload.DiscardUnknown(m)
}

var xxx_messageInfo_I2CPayload proto.InternalMessageInfo

func (m *I2CPayload) GetBus() int32 {
	if m != nil {
		return m.Bus
	}
	return 0
}

func (m *I2CPayload) GetAddr() int32 {
	if m != nil {
		return m.Addr
	}
	return 0
}

func (m *I2CPayload) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *I2CPayload) GetAngle() int32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

type I2CPayloadRes struct {
	Bus                  int32    `protobuf:"varint,1,opt,name=bus,proto3" json:"bus,omitempty"`
	Addr                 int32    `protobuf:"varint,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Index                int32    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Angle                int32    `protobuf:"varint,4,opt,name=angle,proto3" json:"angle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *I2CPayloadRes) Reset()         { *m = I2CPayloadRes{} }
func (m *I2CPayloadRes) String() string { return proto.CompactTextString(m) }
func (*I2CPayloadRes) ProtoMessage()    {}
func (*I2CPayloadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_16cef6ccd09761b2, []int{17}
}

func (m *I2CPayloadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_I2CPayloadRes.Unmarshal(m, b)
}
func (m *I2CPayloadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_I2CPayloadRes.Marshal(b, m, deterministic)
}
func (m *I2CPayloadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_I2CPayloadRes.Merge(m, src)
}
func (m *I2CPayloadRes) XXX_Size() int {
	return xxx_messageInfo_I2CPayloadRes.Size(m)
}
func (m *I2CPayloadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_I2CPayloadRes.DiscardUnknown(m)
}

var xxx_messageInfo_I2CPayloadRes proto.InternalMessageInfo

func (m *I2CPayloadRes) GetBus() int32 {
	if m != nil {
		return m.Bus
	}
	return 0
}

func (m *I2CPayloadRes) GetAddr() int32 {
	if m != nil {
		return m.Addr
	}
	return 0
}

func (m *I2CPayloadRes) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *I2CPayloadRes) GetAngle() int32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func init() {
	proto.RegisterType((*MqttDeviceRequest)(nil), "MqttDeviceRequest")
	proto.RegisterType((*MqttDeviceResponse)(nil), "MqttDeviceResponse")
	proto.RegisterType((*ConfigRes)(nil), "ConfigRes")
	proto.RegisterType((*ConfigPayload)(nil), "ConfigPayload")
	proto.RegisterType((*RunTimeRes)(nil), "RunTimeRes")
	proto.RegisterType((*RunTimePayload)(nil), "RunTimePayload")
	proto.RegisterType((*ErrBadArgsRes)(nil), "ErrBadArgsRes")
	proto.RegisterType((*Heartbeat)(nil), "Heartbeat")
	proto.RegisterType((*HeartbeatRes)(nil), "HeartbeatRes")
	proto.RegisterType((*HeartbeatReq)(nil), "HeartbeatReq")
	proto.RegisterType((*HeartbeatSelectRes)(nil), "HeartbeatSelectRes")
	proto.RegisterType((*HeartbeatSelectReq)(nil), "HeartbeatSelectReq")
	proto.RegisterType((*GpioDigitalPayload)(nil), "GpioDigitalPayload")
	proto.RegisterType((*GpioDigitalPayloadRes)(nil), "GpioDigitalPayloadRes")
	proto.RegisterType((*GpioAnalogPayload)(nil), "GpioAnalogPayload")
	proto.RegisterType((*GpioAnalogPayloadRes)(nil), "GpioAnalogPayloadRes")
	proto.RegisterType((*I2CPayload)(nil), "I2cPayload")
	proto.RegisterType((*I2CPayloadRes)(nil), "I2cPayloadRes")
}

func init() { proto.RegisterFile("esp8266_mqtt.proto", fileDescriptor_16cef6ccd09761b2) }

var fileDescriptor_16cef6ccd09761b2 = []byte{
	// 671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x5d, 0x4f, 0x13, 0x4d,
	0x14, 0xc7, 0x81, 0x52, 0xa0, 0xa7, 0x2f, 0xcf, 0xc3, 0x11, 0xc8, 0xde, 0x18, 0xc9, 0x42, 0xb4,
	0x51, 0xec, 0x45, 0x55, 0x42, 0x82, 0xd1, 0x80, 0x18, 0xca, 0x85, 0x89, 0x59, 0xbc, 0x76, 0x33,
	0xdd, 0x1d, 0xb6, 0x13, 0xcb, 0xbe, 0xcc, 0x4c, 0x89, 0x7e, 0x4d, 0xbf, 0x83, 0xdf, 0xc3, 0xcc,
	0x4b, 0x77, 0xb7, 0xec, 0x36, 0x62, 0xe2, 0xdd, 0x9c, 0x33, 0xff, 0xff, 0xd9, 0x39, 0xfd, 0x9d,
	0x99, 0x02, 0x52, 0x91, 0x9e, 0x0c, 0x8f, 0x8f, 0xfd, 0xdb, 0x4c, 0xca, 0x41, 0xca, 0x13, 0x99,
	0xb8, 0x3f, 0x1b, 0xb0, 0xfd, 0x29, 0x93, 0xf2, 0x82, 0xde, 0xb1, 0x80, 0x7a, 0x34, 0x9b, 0x51,
	0x21, 0xf1, 0x31, 0x80, 0xa0, 0x42, 0xb0, 0x24, 0xf6, 0x59, 0xe8, 0xac, 0xee, 0xaf, 0xf6, 0x9b,
	0x5e, 0xcb, 0x66, 0xae, 0x42, 0x3c, 0x81, 0x4e, 0x94, 0xb2, 0xc4, 0x0f, 0x59, 0xc4, 0x24, 0x99,
	0x3a, 0x6b, 0xfb, 0xab, 0xfd, 0xf6, 0xf0, 0xd1, 0xe0, 0x32, 0x65, 0xc9, 0x85, 0xc9, 0x7d, 0x26,
	0x3f, 0xa6, 0x09, 0x09, 0x47, 0x2b, 0x5e, 0x3b, 0x2a, 0xb2, 0xf8, 0x06, 0x74, 0xe8, 0x93, 0x98,
	0x4c, 0x93, 0xc8, 0x69, 0x68, 0x23, 0x6a, 0xe3, 0x99, 0x4e, 0x15, 0x3e, 0x88, 0xf2, 0x24, 0x3e,
	0x81, 0x06, 0x1b, 0x06, 0xce, 0xba, 0x96, 0xb7, 0x07, 0x57, 0xc3, 0xa0, 0xd0, 0xa9, 0x1d, 0x7c,
	0x0e, 0xad, 0x09, 0x25, 0x5c, 0x8e, 0x29, 0x91, 0x4e, 0xa8, 0x65, 0x30, 0x18, 0xcd, 0x33, 0xa3,
	0x15, 0xaf, 0xd8, 0xc6, 0x4b, 0xd8, 0xc9, 0x03, 0x5f, 0xd0, 0x29, 0x0d, 0xa4, 0xcf, 0xa9, 0x70,
	0xa8, 0xed, 0x22, 0xb7, 0x5d, 0xeb, 0x3d, 0x8f, 0x8a, 0xd1, 0x8a, 0x87, 0x93, 0x4a, 0x16, 0x5f,
	0x43, 0xb7, 0x28, 0xa4, 0x2a, 0xdc, 0xe8, 0x0a, 0xdd, 0xa2, 0x82, 0xf1, 0x76, 0x26, 0xa5, 0x18,
	0x8f, 0x60, 0x8b, 0xcf, 0x62, 0x5f, 0xb2, 0x5b, 0xea, 0x44, 0xda, 0xf0, 0xdf, 0xc0, 0x9b, 0xc5,
	0x5f, 0xd8, 0x2d, 0x2d, 0x9a, 0xda, 0xe4, 0x26, 0x83, 0x7d, 0xd8, 0x08, 0x92, 0xf8, 0x86, 0x45,
	0xce, 0x44, 0x6b, 0x7b, 0x83, 0x0f, 0x3a, 0x2c, 0xa4, 0x76, 0xff, 0xbc, 0x05, 0x9b, 0xa9, 0x49,
	0xba, 0xbf, 0x1a, 0x80, 0x65, 0xa8, 0x22, 0x4d, 0x62, 0x41, 0xf1, 0xb4, 0x16, 0xdb, 0x5e, 0x0d,
	0x36, 0x73, 0xee, 0x05, 0x72, 0x27, 0x75, 0xe4, 0x76, 0xab, 0xe4, 0x8c, 0xb5, 0x0c, 0xcf, 0x2d,
	0xc3, 0xeb, 0x95, 0xe0, 0x19, 0xa9, 0xe6, 0xf7, 0x02, 0xb6, 0xc6, 0x24, 0xf4, 0x09, 0x8f, 0x84,
	0x13, 0x58, 0xe1, 0x47, 0xce, 0xcf, 0x49, 0x78, 0xc6, 0x23, 0x61, 0x84, 0x9b, 0x63, 0x13, 0x2d,
	0x01, 0x98, 0x59, 0xee, 0x35, 0x00, 0xb3, 0x5a, 0x80, 0x19, 0xbe, 0x2c, 0x4f, 0x0d, 0xad, 0x87,
	0x57, 0x1a, 0x9c, 0x7b, 0xbc, 0xb3, 0x3a, 0xde, 0xd9, 0x3d, 0xde, 0x19, 0xf6, 0x2b, 0xbc, 0xdb,
	0x73, 0xde, 0xb6, 0xaf, 0x39, 0xeb, 0xc3, 0x7b, 0xac, 0xc1, 0xb2, 0x36, 0xb2, 0x1a, 0xce, 0x07,
	0xd0, 0xca, 0x15, 0xb8, 0x97, 0xbb, 0xcd, 0x7d, 0xb5, 0x91, 0xfb, 0x0c, 0xba, 0x0b, 0x23, 0xb3,
	0x54, 0xf8, 0x0d, 0xa0, 0x38, 0x17, 0x22, 0xac, 0xeb, 0x23, 0x2b, 0x4d, 0xc3, 0xd3, 0x6b, 0x3c,
	0x84, 0x1e, 0x49, 0x53, 0x5f, 0x48, 0xc2, 0xa5, 0x69, 0x68, 0x4d, 0xef, 0x76, 0x48, 0x9a, 0x5e,
	0xab, 0xa4, 0x6e, 0xe3, 0x00, 0xba, 0x9c, 0x16, 0x1a, 0xa1, 0x67, 0xa5, 0xe9, 0x75, 0x6c, 0x52,
	0x69, 0x84, 0x7b, 0x08, 0xbd, 0xc5, 0xa1, 0x5f, 0xf8, 0x60, 0xd3, 0x7c, 0xd0, 0x3d, 0x80, 0xee,
	0xc2, 0x14, 0x28, 0x51, 0x90, 0x84, 0xb9, 0x48, 0xad, 0xd5, 0xaf, 0x90, 0x03, 0x50, 0xcd, 0x09,
	0x49, 0xe4, 0x4c, 0xcc, 0x9b, 0x33, 0x91, 0xfb, 0x14, 0x3a, 0x65, 0xb0, 0x0f, 0xd4, 0x65, 0x4b,
	0x75, 0x47, 0x80, 0xd5, 0x77, 0xe2, 0xaf, 0xd4, 0xcb, 0x6b, 0xbf, 0x05, 0xac, 0x5e, 0x49, 0xfc,
	0x1f, 0x1a, 0x29, 0x8b, 0xad, 0x54, 0x2d, 0x71, 0x07, 0x9a, 0x77, 0x64, 0x3a, 0x33, 0x14, 0x9a,
	0x9e, 0x09, 0xdc, 0xf7, 0xb0, 0x5b, 0x7b, 0xa1, 0x1f, 0x5c, 0xe0, 0x14, 0xb6, 0x2b, 0xb7, 0xfa,
	0x4f, 0xe6, 0xb5, 0xb9, 0xf9, 0x1d, 0xec, 0xd4, 0x3d, 0x09, 0x0f, 0xf6, 0x7f, 0x05, 0x28, 0x1e,
	0x08, 0xe5, 0x1a, 0xe7, 0x3f, 0x8f, 0x5a, 0xaa, 0x01, 0x20, 0x61, 0xc8, 0xed, 0x89, 0xf5, 0x5a,
	0x55, 0x62, 0x71, 0x48, 0xbf, 0xdb, 0x41, 0x33, 0x81, 0xca, 0x92, 0x38, 0x9a, 0x52, 0xfd, 0xf0,
	0x34, 0x3d, 0x13, 0xb8, 0x04, 0xba, 0x0b, 0x0f, 0xd0, 0xbf, 0xff, 0xc4, 0x78, 0x43, 0xff, 0xb3,
	0xbe, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x55, 0x14, 0x83, 0xfd, 0x6f, 0x07, 0x00, 0x00,
}
