package metathings_deviced_service

const (
	KIND_DEVICE = "deviced:device"
	KIND_MODULE = "deviced:module"
	KIND_FLOW   = "deviced:flow"

	RESOURCE_TYPE_FLOW    = "flow"
	RESOURCE_TYPE_FLOWSET = "flowset"

	DEVICED_PUSH_FRAME_TO_FLOW_ONCE                      = "deviced:push_frame_to_flow_once"
	DEVICED_LIST_FIRMWARE_HUBS                           = "deviced:list_firmware_hubs"
	DEVICED_PATCH_CONFIG                                 = "deviced:patch_config"
	DEVICED_REMOVE_FIRMWARE_DESCRIPTOR_FROM_FIRMWARE_HUB = "deviced:remove_firmware_descriptor_from_firmware_hub"
	DEVICED_PATCH_FLOW_SET                               = "deviced:patch_flow_set"
	DEVICED_GET_DEVICE_BY_MODULE                         = "deviced:get_device_by_module"
	DEVICED_DELETE_CONFIG                                = "deviced:delete_config"
	DEVICED_ADD_FLOWS_TO_FLOW_SET                        = "deviced:add_flows_to_flow_set"
	DEVICED_GET_FLOW_SET                                 = "deviced:get_flow_set"
	DEVICED_PATCH_DEVICE                                 = "deviced:patch_device"
	DEVICED_SYNC_DEVICE_FIRMWARE_DESCRIPTOR              = "deviced:sync_device_firmware_descriptor"
	DEVICED_PATCH_FIRMWARE_HUB                           = "deviced:patch_firmware_hub"
	DEVICED_DELETE_DEVICE                                = "deviced:delete_device"
	DEVICED_GET_OBJECT_CONTENT                           = "deviced:get_object_content"
	DEVICED_GET_DEVICE                                   = "deviced:get_device"
	DEVICED_REMOVE_DEVICES_FROM_FIRMWARE_HUB             = "deviced:remove_devices_from_firmware_hub"
	DEVICED_DELETE_FLOW_SET                              = "deviced:delete_flow_set"
	DEVICED_ADD_DEVICES_TO_FIRMWARE_HUB                  = "deviced:add_devices_to_firmware_hub"
	DEVICED_REMOVE_CONFIGS_FROM_DEVICE                   = "deviced:remove_configs_from_device"
	DEVICED_REMOVE_OBJECT                                = "deviced:remove_object"
	DEVICED_UNARY_CALL                                   = "deviced:unary_call"
	DEVICED_LIST_CONFIGS_BY_DEVICE                       = "deviced:list_configs_by_device"
	DEVICED_PUT_OBJECT                                   = "deviced:put_object"
	DEVICED_ADD_CONFIGS_TO_DEVICE                        = "deviced:add_configs_to_device"
	DEVICED_RENAME_OBJECT                                = "deviced:rename_object"
	DEVICED_REMOVE_FLOWS_FROM_FLOW_SET                   = "deviced:remove_flows_from_flow_set"
	DEVICED_LIST_OBJECTS                                 = "deviced:list_objects"
	DEVICED_DELETE_FIRMWARE_HUB                          = "deviced:delete_firmware_hub"
	DEVICED_CREATE_FIRMWARE_HUB                          = "deviced:create_firmware_hub"
	DEVICED_SET_DEVICE_FIRMWARE_DESCRIPTOR               = "deviced:set_device_firmware_descriptor"
	DEVICED_GET_FIRMWARE_HUB                             = "deviced:get_firmware_hub"
	DEVICED_GET_CONFIG                                   = "deviced:get_config"
	DEVICED_ADD_FIRMWARE_DESCRIPTOR_TO_FIRMWARE_HUB      = "deviced:add_firmware_descriptor_to_firmware_hub"
	DEVICED_HEARTBEAT                                    = "deviced:heartbeat"
	DEVICED_GET_OBJECT                                   = "deviced:get_object"
)
