// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: stream_call.proto

package component

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _stream_call_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on StreamCallRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *StreamCallRequest) Validate() error {
	if m == nil {
		return nil
	}

	switch m.Request.(type) {

	case *StreamCallRequest_Config:

		if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return StreamCallRequestValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *StreamCallRequest_Data:

		if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return StreamCallRequestValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// StreamCallRequestValidationError is the validation error returned by
// StreamCallRequest.Validate if the designated constraints aren't met.
type StreamCallRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamCallRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamCallRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamCallRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamCallRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamCallRequestValidationError) ErrorName() string {
	return "StreamCallRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StreamCallRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamCallRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamCallRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamCallRequestValidationError{}

// Validate checks the field values on StreamCallConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *StreamCallConfigRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetMethod() == nil {
		return StreamCallConfigRequestValidationError{
			field:  "Method",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetMethod()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StreamCallConfigRequestValidationError{
				field:  "Method",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// StreamCallConfigRequestValidationError is the validation error returned by
// StreamCallConfigRequest.Validate if the designated constraints aren't met.
type StreamCallConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamCallConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamCallConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamCallConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamCallConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamCallConfigRequestValidationError) ErrorName() string {
	return "StreamCallConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StreamCallConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamCallConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamCallConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamCallConfigRequestValidationError{}

// Validate checks the field values on StreamCallDataRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *StreamCallDataRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetValue() == nil {
		return StreamCallDataRequestValidationError{
			field:  "Value",
			reason: "value is required",
		}
	}

	if a := m.GetValue(); a != nil {

	}

	return nil
}

// StreamCallDataRequestValidationError is the validation error returned by
// StreamCallDataRequest.Validate if the designated constraints aren't met.
type StreamCallDataRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamCallDataRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamCallDataRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamCallDataRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamCallDataRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamCallDataRequestValidationError) ErrorName() string {
	return "StreamCallDataRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StreamCallDataRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamCallDataRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamCallDataRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamCallDataRequestValidationError{}

// Validate checks the field values on StreamCallResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *StreamCallResponse) Validate() error {
	if m == nil {
		return nil
	}

	switch m.Response.(type) {

	case *StreamCallResponse_Config:

		if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return StreamCallResponseValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *StreamCallResponse_Data:

		if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return StreamCallResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// StreamCallResponseValidationError is the validation error returned by
// StreamCallResponse.Validate if the designated constraints aren't met.
type StreamCallResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamCallResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamCallResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamCallResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamCallResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamCallResponseValidationError) ErrorName() string {
	return "StreamCallResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StreamCallResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamCallResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamCallResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamCallResponseValidationError{}

// Validate checks the field values on StreamCallConfigResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *StreamCallConfigResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Method

	return nil
}

// StreamCallConfigResponseValidationError is the validation error returned by
// StreamCallConfigResponse.Validate if the designated constraints aren't met.
type StreamCallConfigResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamCallConfigResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamCallConfigResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamCallConfigResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamCallConfigResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamCallConfigResponseValidationError) ErrorName() string {
	return "StreamCallConfigResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StreamCallConfigResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamCallConfigResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamCallConfigResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamCallConfigResponseValidationError{}

// Validate checks the field values on StreamCallDataResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *StreamCallDataResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StreamCallDataResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// StreamCallDataResponseValidationError is the validation error returned by
// StreamCallDataResponse.Validate if the designated constraints aren't met.
type StreamCallDataResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamCallDataResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamCallDataResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamCallDataResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamCallDataResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamCallDataResponseValidationError) ErrorName() string {
	return "StreamCallDataResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StreamCallDataResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamCallDataResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamCallDataResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamCallDataResponseValidationError{}
