all:
	$(MAKE) -C common all
	$(MAKE) -C identityd all
	$(MAKE) -C cored all
	$(MAKE) -C camerad all
	$(MAKE) -C core_agent all
	$(MAKE) -C echo all
	$(MAKE) -C switcher all
	$(MAKE) -C motor all
	$(MAKE) -C camera all
	$(MAKE) -C servo all
	$(MAKE) -C sensor all
