all:
	$(MAKE) -C common all
	$(MAKE) -C constant all
	$(MAKE) -C component all
	$(MAKE) -C component_ext all
	$(MAKE) -C policyd all
	$(MAKE) -C identityd2 all
	$(MAKE) -C deviced all
	$(MAKE) -C component all
	$(MAKE) -C device all
	$(MAKE) -C tagd all
	$(MAKE) -C evaluatord all
