name: Compile Binary and Upload Asset
on:
  release:
    types: [created]

jobs:
  compile-metathingsd-and-upload-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "darwin"]
        goarch: ["amd64"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.12"
      - name: Compile Metathingsd Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -o metathingsd cmd/metathingsd/main.go
          tar zcvf metathingsd.tar.gz metathingsd
      - name: Upload Metathingsd Asset
        uses: PeerXu/upload-asset@v1
        with:
          file: metathingsd.tar.gz
          os: ${{ matrix.goos }}
          arch: ${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  compile-metathings-and-upload-asset:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "darwin"]
        goarch: ["amd64", "arm", "arm64"]
        exclude:
        - goos: darwin
          goarch: arm
        - goos: darwin
          goarch: arm64
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.12"
      - name: Compile Metathings Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -o metathings cmd/metathings/main.go
          tar zcvf metathings.tar.gz metathings
      - name: Upload Metathings Asset
        uses: PeerXu/upload-asset@v1
        with:
          file: metathings.tar.gz
          os: ${{ matrix.goos }}
          arch: ${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
