// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: create_region.proto

package identityd

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CreateRegionRequest) Validate() error {
	if nil == this.Id {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf("message must exist"))
	}
	if this.Id != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Id); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Id", err)
		}
	}
	if this.ParentRegionId != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ParentRegionId); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ParentRegionId", err)
		}
	}
	if this.Description != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Description); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Description", err)
		}
	}
	return nil
}
func (this *CreateRegionResponse) Validate() error {
	if this.Region != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Region); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Region", err)
		}
	}
	return nil
}
