// Code generated by protoc-gen-go. DO NOT EDIT.
// source: list_role_in_group_on_domain.proto

package identityd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRoleInGroupOnDomainRequest struct {
	DomainId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=domain_id,json=domainId" json:"domain_id,omitempty"`
	GroupId              *wrappers.StringValue `protobuf:"bytes,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListRoleInGroupOnDomainRequest) Reset()         { *m = ListRoleInGroupOnDomainRequest{} }
func (m *ListRoleInGroupOnDomainRequest) String() string { return proto.CompactTextString(m) }
func (*ListRoleInGroupOnDomainRequest) ProtoMessage()    {}
func (*ListRoleInGroupOnDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_role_in_group_on_domain_58512ba3a42c9d26, []int{0}
}
func (m *ListRoleInGroupOnDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoleInGroupOnDomainRequest.Unmarshal(m, b)
}
func (m *ListRoleInGroupOnDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoleInGroupOnDomainRequest.Marshal(b, m, deterministic)
}
func (dst *ListRoleInGroupOnDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoleInGroupOnDomainRequest.Merge(dst, src)
}
func (m *ListRoleInGroupOnDomainRequest) XXX_Size() int {
	return xxx_messageInfo_ListRoleInGroupOnDomainRequest.Size(m)
}
func (m *ListRoleInGroupOnDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoleInGroupOnDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoleInGroupOnDomainRequest proto.InternalMessageInfo

func (m *ListRoleInGroupOnDomainRequest) GetDomainId() *wrappers.StringValue {
	if m != nil {
		return m.DomainId
	}
	return nil
}

func (m *ListRoleInGroupOnDomainRequest) GetGroupId() *wrappers.StringValue {
	if m != nil {
		return m.GroupId
	}
	return nil
}

type ListRoleInGroupOnDomainResponse struct {
	Roles                []*Role  `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoleInGroupOnDomainResponse) Reset()         { *m = ListRoleInGroupOnDomainResponse{} }
func (m *ListRoleInGroupOnDomainResponse) String() string { return proto.CompactTextString(m) }
func (*ListRoleInGroupOnDomainResponse) ProtoMessage()    {}
func (*ListRoleInGroupOnDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_role_in_group_on_domain_58512ba3a42c9d26, []int{1}
}
func (m *ListRoleInGroupOnDomainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoleInGroupOnDomainResponse.Unmarshal(m, b)
}
func (m *ListRoleInGroupOnDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoleInGroupOnDomainResponse.Marshal(b, m, deterministic)
}
func (dst *ListRoleInGroupOnDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoleInGroupOnDomainResponse.Merge(dst, src)
}
func (m *ListRoleInGroupOnDomainResponse) XXX_Size() int {
	return xxx_messageInfo_ListRoleInGroupOnDomainResponse.Size(m)
}
func (m *ListRoleInGroupOnDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoleInGroupOnDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoleInGroupOnDomainResponse proto.InternalMessageInfo

func (m *ListRoleInGroupOnDomainResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRoleInGroupOnDomainRequest)(nil), "ai.metathings.service.identityd.ListRoleInGroupOnDomainRequest")
	proto.RegisterType((*ListRoleInGroupOnDomainResponse)(nil), "ai.metathings.service.identityd.ListRoleInGroupOnDomainResponse")
}

func init() {
	proto.RegisterFile("list_role_in_group_on_domain.proto", fileDescriptor_list_role_in_group_on_domain_58512ba3a42c9d26)
}

var fileDescriptor_list_role_in_group_on_domain_58512ba3a42c9d26 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd0, 0xc1, 0x4a, 0x33, 0x31,
	0x10, 0x07, 0x70, 0xb6, 0x1f, 0x5f, 0xad, 0xe9, 0x6d, 0x4f, 0xa5, 0x48, 0x5b, 0x0a, 0x42, 0x2f,
	0xcd, 0x42, 0x05, 0x2f, 0x1e, 0x44, 0x11, 0xa4, 0x20, 0x08, 0x2b, 0x78, 0x74, 0x49, 0x9b, 0x31,
	0x1d, 0xcc, 0x66, 0xd6, 0x64, 0xb6, 0x8b, 0xef, 0xe3, 0x7b, 0x09, 0x3e, 0x89, 0xec, 0x46, 0xbd,
	0x89, 0x78, 0x1b, 0x48, 0xfe, 0x7f, 0x7e, 0x33, 0x62, 0x6e, 0x31, 0x70, 0xe1, 0xc9, 0x42, 0x81,
	0xae, 0x30, 0x9e, 0xea, 0xaa, 0x20, 0x57, 0x68, 0x2a, 0x15, 0x3a, 0x59, 0x79, 0x62, 0x4a, 0xa7,
	0x0a, 0x65, 0x09, 0xac, 0x78, 0x87, 0xce, 0x04, 0x19, 0xc0, 0xef, 0x71, 0x0b, 0x12, 0x35, 0x38,
	0x46, 0x7e, 0xd1, 0xe3, 0x89, 0x21, 0x32, 0x16, 0xb2, 0xee, 0xfb, 0xa6, 0x7e, 0xcc, 0x1a, 0xaf,
	0xaa, 0x0a, 0x7c, 0x88, 0x05, 0xe3, 0x53, 0x83, 0xbc, 0xab, 0x37, 0x72, 0x4b, 0x65, 0x56, 0x36,
	0xc8, 0x4f, 0xd4, 0x64, 0x86, 0x96, 0xdd, 0xe3, 0x72, 0xaf, 0x2c, 0x6a, 0xc5, 0xe4, 0x43, 0xf6,
	0x3d, 0x7e, 0xe6, 0x44, 0xeb, 0x8a, 0xf3, 0xfc, 0x35, 0x11, 0x93, 0x1b, 0x0c, 0x9c, 0x93, 0x85,
	0xb5, 0xbb, 0x6e, 0xa1, 0xb7, 0xee, 0xaa, 0x63, 0xe6, 0xf0, 0x5c, 0x43, 0xe0, 0xf4, 0x42, 0x1c,
	0x46, 0x77, 0x81, 0x7a, 0x94, 0xcc, 0x92, 0xc5, 0x70, 0x75, 0x24, 0x23, 0x4d, 0x7e, 0xd1, 0xe4,
	0x1d, 0x7b, 0x74, 0xe6, 0x5e, 0xd9, 0x1a, 0x2e, 0xfb, 0xef, 0x6f, 0xd3, 0xde, 0x2c, 0xc9, 0x07,
	0x31, 0xb6, 0xd6, 0xe9, 0xb9, 0x18, 0xc4, 0x1b, 0xa0, 0x1e, 0xf5, 0xfe, 0xd0, 0x70, 0xd0, 0xa5,
	0xd6, 0x7a, 0xfe, 0x20, 0xa6, 0x3f, 0x2a, 0x43, 0x45, 0x2e, 0x40, 0x7a, 0x26, 0xfe, 0xb7, 0x7b,
	0x85, 0x51, 0x32, 0xfb, 0xb7, 0x18, 0xae, 0x8e, 0xe5, 0x2f, 0xe7, 0x95, 0x6d, 0x59, 0x1e, 0x33,
	0x9b, 0x7e, 0xc7, 0x38, 0xf9, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xb6, 0x9f, 0xe1, 0xb8, 0x01,
	0x00, 0x00,
}
