// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get.proto

package sensord

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_2081772d4b15c4e8, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetResponse struct {
	Sensor               *Sensor  `protobuf:"bytes,1,opt,name=sensor" json:"sensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_2081772d4b15c4e8, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "ai.metathings.service.sensord.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "ai.metathings.service.sensord.GetResponse")
}

func init() { proto.RegisterFile("get.proto", fileDescriptor_get_2081772d4b15c4e8) }

var fileDescriptor_get_2081772d4b15c4e8 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x49, 0x8a, 0x80, 0x7b, 0x56, 0xa9, 0xe4, 0xf0, 0xcf, 0x71, 0x20, 0xd8, 0xdc, 0x2c,
	0xa8, 0xd8, 0xd9, 0x5c, 0x63, 0x63, 0x95, 0x03, 0xfb, 0xcd, 0x65, 0xdc, 0x1b, 0x4c, 0x32, 0x71,
	0x67, 0x92, 0x7c, 0x5c, 0xc1, 0x4f, 0x22, 0xec, 0x46, 0x4b, 0xab, 0x99, 0x61, 0xe6, 0xbd, 0xdf,
	0x1b, 0x73, 0xe6, 0x51, 0x61, 0x08, 0xac, 0x5c, 0x5e, 0x39, 0x82, 0x0e, 0xd5, 0xe9, 0x89, 0x7a,
	0x2f, 0x20, 0x18, 0x26, 0x3a, 0x22, 0x08, 0xf6, 0xc2, 0xa1, 0x59, 0x5f, 0x7b, 0x66, 0xdf, 0xa2,
	0x8d, 0xc7, 0xf5, 0xf8, 0x6e, 0xe7, 0xe0, 0x86, 0x01, 0x83, 0x24, 0xf9, 0xfa, 0xc9, 0x93, 0x9e,
	0xc6, 0x1a, 0x8e, 0xdc, 0xd9, 0x6e, 0x26, 0xfd, 0xe0, 0xd9, 0x7a, 0xde, 0xc5, 0xe5, 0x6e, 0x72,
	0x2d, 0x35, 0x4e, 0x39, 0x88, 0xfd, 0x6b, 0x17, 0xdd, 0x79, 0x02, 0xa4, 0x69, 0xbb, 0x37, 0xe6,
	0x05, 0xb5, 0xc2, 0xcf, 0x11, 0x45, 0xcb, 0x47, 0x93, 0x53, 0x73, 0x91, 0x6d, 0xb2, 0xbb, 0xd5,
	0xfd, 0x25, 0xa4, 0x00, 0xf0, 0x1b, 0x00, 0x0e, 0x1a, 0xa8, 0xf7, 0x6f, 0xae, 0x1d, 0x71, 0x5f,
	0x7c, 0x7f, 0xdd, 0xe4, 0x9b, 0xac, 0xca, 0xa9, 0xd9, 0xbe, 0x9a, 0x55, 0xf4, 0x90, 0x81, 0x7b,
	0xc1, 0xf2, 0xd9, 0x14, 0x09, 0xb1, 0x18, 0xdd, 0xc2, 0xbf, 0x8f, 0xc2, 0x21, 0xd6, 0x6a, 0x11,
	0xd5, 0x45, 0xe4, 0x3d, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xb3, 0x55, 0x74, 0x2a, 0x01,
	0x00, 0x00,
}
