// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sensor.proto

package sensord

import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/nayotta/metathings/pkg/proto/sensor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Sensor) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *SensorData) Validate() error {
	if this.CreatedAt != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.ArrivedAt != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.ArrivedAt); err != nil {
			return go_proto_validators.FieldError("ArrivedAt", err)
		}
	}
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
